
<?php
if($arreglo){

 if($disponible){?>
<span class="true"><?php echo $registro->nombre('reversa') ?></span>|
<?php }else if($invalido){?>
<span class="false"><?php echo $invalido?></span>|
<?php }else if($valor != ''){?>
<span class="false">No disponible</span>|
<?php } ?>

<?php echo $disponible;


}else{
 if($disponible){?>
<span class="true"><?php echo $registro->nombre('reversa') ?></span>
<?php }else if($invalido){?>
<span class="false"><?php echo $invalido?></span>
<?php }else if($valor != ''){?>
<span class="false">No disponible</span>
<?php } ?>
<input type="hidden" id="disponible" value="<?php echo $disponible?>" />
<?php  } ?>