<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Agregar tutor</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>tutores">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) { 
                case 'captura': ?>
                <form action="<?php echo $path ?>tutores/agregar" id="frm_agregar" method="post" enctype="multipart/form-data">
                    <fieldset>
                        <legend>Datos del alumno</legend>
                        <label>C&oacute;digo
                            <br />
                            <input type="text" name="alumnos_id[]" id="alumnos_id" size="20" maxlength="20" class="codigo"/>
                        </label>
                        <img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
                        <br />
                        <div id="check" class="check"></div>
                        <div id="codigos1" class="codigos"></div>
                        <a href="#" id="bMas"><img src="<?php echo $path . 'img/sp5/mas.png' ?>" /></a>
                        <br />
                    </fieldset>
                    <div class="divisor"></div>
                    <fieldset>
                        <legend>Datos del tutor</legend>
                        <label for="nombre">Nombre</label><br />
                        <input type="text" name="nombre" id="nombre" size="30" maxlength="30" /><br />
                        <label for="ap">Apellido paterno</label><br />
                        <input type="text" name="ap" id="ap" size="20" maxlength="20" /><br />
                        <label for="am">Apellido materno</label><br />
                        <input type="text" name="am" id="am" size="20" maxlength="20" />
                        <label><input type="radio" name="sexo" value="M" id="mujer"/> Mujer </label>
                        <label><input type="radio" name="sexo" value="H" id="hombre"/> Hombre </label><br />
                        <label for="fnacimiento">Fecha de nacimiento</label><br />
                        <input type="text" name="fnacimiento" id="fnacimiento" size="10" maxlength="10" />
                        <a id="b1"><img src="<?php echo $path ?>/public/img/sp5/calendario.png" /></a><br />
                        <label for="foto">Foto</label><br />
                        <input type="file" id="foto" name="foto" /><br />
                    </fieldset>
                    <div class="divisor"></div>
                    <fieldset>
                        <legend>Contacto</legend>
                        <label for="domicilio">Domicilio</label><br />
                        <input type="text" name="domicilio" id="domicilio" size="30" maxlength="60" /><br />
                        <label for="tel">Tel&eacute;fono</label><br />
                        <input type="text" name="tel" id="tel" size="20" maxlength="20" /><br />
                        <label for="cel">Tel&eacute;fono m&oacute;vil</label><br />
                        <input type="text" name="cel" id="cel" size="20" maxlength="20" /><br />
                        <label for="mail">Correo electr&oacute;nico</label><br />
                        <input type="text" name="mail" id="mail" size="30" maxlength="80" /><br />
                    </fieldset>
                    <div id="botones">
                        <input type="button" id="cancelar" value="Cancelar">
                        <input type="button" id="agregar" value="Agregar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info">
                    <br />
                    El tutor se agreg&oacute; correctamente
                    <?php echo $exito ?>
                </p>
            <?php  break; ?>
            <?php case 'error': 
                  default: 
            ?>
                <p class="error"><br />Ha ocurrido un error al intentar agregar el tutor
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>