<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Datos del tutor</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>tutores">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <table>
        <tr><th>#</th><th>Alumno</th><th>Tutor</th><th>Msj</th></tr>
        <?php
            $i=1;
            $e=0;
            $o=0;
         foreach($casos as $caso){
            $alumno=$caso['a'];
            if($caso['t']==1){
                $o++;
            }else{
                $e++;
                }
            ?>
        <tr><td><?php echo $i; ?></td><td><?php echo $alumno->nombre(); ?></td><td><?php echo  "Tutor Paterno ".$alumno->codigo; ?></td><td><?php echo $caso['e']; ?></td></tr>
        <?php
        $i++;
        }
        ?>
        </table>

        <table>
        <tr><th>Guardados</th<td><?php echo $o; ?></td></tr>
        <tr><th>Errores</th<td><?php  echo $e; ?></td></tr>
        <tr><th>Total</th<td><?php  echo count($casos); ?></td></tr>

        </table>
    </div>
</div>