<div id="primary">
	<div class="content">
	    
        <?php if($evento == sha1('err_login')){ ?>
        <p class="error"><br />Nombre de usuario o contrase&ntilde;a incorrecta</p>
        <?php } ?>
	    <div style="float: left;margin-left: 20%;">
		<form action="<?php echo KUMBIA_PATH ?>sesion/abrir" method="post" id="frm_auth">
			<fieldset>
				<legend>Iniciar sesi&oacute;n</legend>
				<div>
					<label for="login">Usuario</label>
					<input name="login" id="login" type="text" size="15" maxlength="25"  >
				</div>
				<div>
					<label for="pass">Contrase&ntilde;a</label>
					<input name="pass" type="password" id="pass" size="15" maxlength="25" >
				</div>
				<input type="submit" id="aceptar" value=".: Entrar" class="btn_aceptar"/>
			</fieldset>
		</form>
		</div>
		<div id="informacion_usuarios">
		    <p>Hekademos cuenta con diferentes privilegios seg&uacute;n el tipo de usuario.</p>
		        <p>Puede ingresar con las siguientes cuentas de usuario:</p>
		    <p>
		        <ul>
		        <li>administrador</li>
		        <li>disciplina</li>
		        <li>oficial</li>
		        <li>secretaria</li>
		        <li>plantilla</li>
		        <li>director</li>
		        <li>secretario</li>
		        </ul>
		    </p>
		    <p>La contraseña para todas las cuentas es <span style="font-weight: bold">hekademos</span>.</p>
		</div>
		
	</div>
</div>
<div id="secondary"><div class="content"></div></div>
<div id="tertiary"><div class="content"></div></div>