<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">


<?php switch($option){
        case 'captura':
     ?>        <h1>Inscribir al curso</h1>
        <h2><?php echo $curso->verMateriaNombre(); ?></h2>
        <h2>Prof. <?php echo $curso->verProfesor(); ?></h2>
        <h2><?php echo $grupo->grado .'&deg;' .  $grupo->letra .  ' ' . $grupo->verTurno() . ', ' . $ciclo->numero?></h2>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>cursos/ver/<?php echo $curso->id; ?>">Volver al curso
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
            <form action="<?php echo $path ?>inscripcion/agregar" id="frm_agregar" method="post" enctype="multipart/form-data">
            <fieldset>
            <legend>Datos del alumno</legend>
            <label>C&oacute;digo
            <br />
            <input type="text" name="alumnos_id[]" id="alumnos_id" size="20" maxlength="20" class="codigo"/>
            </label>
            <input name="curso_id" id="curso_id" type="hidden" value="<?php echo $curso->id; ?>" /><br />
            <label>Articulo<br />
            <select name="articulo[]" id="articulo" class="articulo">
                <option value=""></option>
                <?php
                    foreach($articulos as $articulo){
                    ?>
                    <option value="<?php echo $articulo->id; ?>"><?php echo $articulo->descripcion; ?> </option>
                <?php
                    }
                ?>
              </select>
            </label>
            <img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
            <br />
            <div id="check" class="check"></div>
            <div id="codigos1" class="codigos"></div>
            <a href="#" id="bMas"><img src="<?php echo $path . 'img/sp5/mas.png' ?>" /></a>
            <br />

            </fieldset>
                <div id="botones">
                <input type="button" id="cancelar" value="Cancelar">
                <input type="button" id="agregar" value="Inscribir">
                </div>

            </form>
<?php break;

    case 'exito':
 ?>
         <h1>Inscribir al curso</h1>
        <h2><?php echo $curso->verMateriaNombre(); ?></h2>
        <h2>Prof. <?php echo $curso->verProfesor(); ?></h2>
        <h2><?php echo $grupo->grado .'&deg;' .  $grupo->letra .  ' ' . $grupo->verTurno() . ', ' . $ciclo->numero?></h2>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>cursos/ver/<?php echo $curso->id; ?>">Volver al curso
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
                 <?php if($exito!=''){ ?>
                 <p class="info">
                    <br />
                    Alumnos inscritos  al curso.
                    <?php echo $exito ?>
                </p>
                <?php }  ?>

                <?php if($error!=''){ ?>
                <br/>
                <p class="error"><br />Alumnos no inscritos.
                    <?php echo $error ?>
                </p>

                <?php }  ?>

<?php
    break;
        case 'confirmar':
?>
    <h1>Inscribir al curso</h1>
        <h2><?php echo $curso->verMateriaNombre(); ?></h2>
        <h2>Prof. <?php echo $curso->verProfesor(); ?></h2>
        <h2><?php echo $grupo->grado .'&deg;' .  $grupo->letra .  ' ' . $grupo->verTurno() . ', ' . $ciclo->numero?></h2>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>cursos/ver/<?php echo $curso->id; ?>">Volver al curso
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>

<br/>
<form action="<?php echo $path ?>inscripcion/agregar/" id="frm_agregar" method="post">
                    <p class="error" style="text-align:left;padding-left:100px">

                        Se dispone a inscribir a los alumnos  <br/>
                        <?php
                        foreach($alumnos as $llave => $alumno){
                            $articulo=$articulos[$llave];
                            if(trim($alumno)!=''){
                        ?>
                        <input type="hidden" name="alumnos[]" value="<?php echo $alumno; ?>" />
                        <strong>Codigo:</strong> <?php echo $alumno; ?>
                        <?php
                        $art=new Articulos();
                        $art=$art->find($articulo);
                        if($art->id!=''){ ?>
                        <strong><?php echo $art->descripcion; ?></strong>
                        <input type="hidden" name="articulos[]" value="<?php echo $art->id; ?>" />
                        <?php }else{
                            ?>
                        <input type="hidden" name="articulos[]" value="" />
                        <?php

                        } ?>
                        <br />

                        <?php
                            }
                         } ?>
                        <input type="hidden" name="curso_id" value="<?php echo $curso_id; ?>" />

                        <strong>&iquest;Desea continuar?</strong>
                    </p>
                      <div id="botones">
                        <input type="submit" id="aceptar_c" value="Aceptar">
                        <input type="button" id="cancelar_c" value="Cancelar">

                    </div>
                </form>

<?php
    break;


    case 'error':
 ?>
             <br/>
            <p class="error"><br />Ha ocurrido un error al intentar inscribir.
                    <?php echo $error ?>
                </p>
<?php
    break;

 }?>
    </div>
</div>