<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Editar curso de <?php echo $grupo->grado . '&deg;' . $grupo->letra . ' ' . $grupo->verTurno()?> ciclo <?php echo $ciclo->numero ?></h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path . 'cursos/grupo/' . $grupo->id ?>">Volver al grupo
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>cursos/editar" id="frm_editar" method="post">
                <input type="hidden" name="KUMBIA_PATH" id="KUMBIA_PATH" value="<?php echo $path; ?>" />
                    <fieldset>
                        <legend>Curso</legend>
                        <input type="hidden" name="id" id="id" value="<?php echo $curso->id ?>"/>
                        <input type="hidden" name="ciclos_id" id="ciclos_id" value="<?php echo $ciclo->id ?>"/>
                        <input type="hidden" name="grupos_id" id="grupos_id" value="<?php echo $grupo->id ?>"/>
                        <input type="hidden" id="grupo_oferta" value="<?php echo $grupo->oferta_id; ?>"/>
                        <?php if(!$curso->aprobado() || in_array('root',  $usr_grupos)){ ?>
                        <label for="materias_id">Materia</label><br />
                        <select name="materias_id" id="materias_id">
                            <option></option>
                            <option value="<?php echo $curso->materias_id?>"
                                    selected="selected">
                                <?php echo $curso->verMateriaNombre()?>
                            </option>
                            <?php foreach($materias as $materia){?>
                            <option value="<?php echo $materia->id?>"><?php echo $materia->nombre?></option>
                            <?php } ?>
                        </select>
                        <?php
                            }else{
                          ?>
                              <h2>Materia</h2>
                            <h2><?php echo $curso->verMateriaNombre(); ?></h2>
                            <input type="hidden" name="materias_id" id="materias_id" value="<?php echo  $curso->materias_id; ?>"/>
                        <?php
                            }
                         ?>
                        <br />
                        <label for="profesores_id">Profesor</label><br />
                        <select name="profesores_id" id="profesores_id">
                            <option></option>
                            <option value="<?php echo $curso->profesores_id ?>"
                                    selected="selected">
                                <?php echo $curso->verProfesor()?>
                            </option>
                            <?php foreach($profesores as $profesor){?>
                            <option value="<?php echo $profesor->id?>" alt="<?php echo $profesor->codigo?>">
                                <?php echo $profesor->ap . ' ' . $profesor->am . ', ' .$profesor->nombre?>
                            </option>
                            <?php } ?>
                        </select>
                        <br />
                        <?php
                        if($grupo->oferta_id==2){
                        ?>
                        <?php
                        if($curso->enProceso() || $curso->rechazado()){
                        ?>
                        <div id="div_fecha">
                            <br/>
                            Inicio<br/>
                            <span class="sub"><?php echo Utils::fecha_espanol($curso->inicio); ?></span>
                            <input type="hidden" name="inicio" id="inicio" size="10" maxlength="10" value="<?php echo Utils::convierteFecha($curso->inicio); ?>" />

                        </div>
                        <br />
                        <?php
                        }else{
                        ?>
                        <div id="div_fecha">
                            Inicio<br/>
                            <span class="sub"><?php echo Utils::fecha_espanol($curso->inicio); ?></span>
                            <input type="hidden" name="inicio" id="inicio" size="10" maxlength="10" value="<?php echo Utils::convierteFecha($curso->inicio); ?>" />
                        </div>
                        <br/>
                        <?php
                        }
                        ?>
                        <?php
                        }
                        ?>
                    </fieldset>
                    <div class="separador"></div>
                    <fieldset style="width:600px">
                        <legend>Horario</legend>
                        <table>
                            <tr>
                                <th></th>
                                <th>Inicio</th>
                                <th>Fin</th>
                                <th>Aula</th>
                                <th style="width:200px">Disponible</th>
                            </tr>
                            <?php for($d = 1; $d < 7; $d++){?>
                            <?php $horario = $curso->horario($d) ?>
                            <tr>
                                <th>
                                    <?php echo $dias[$d-1]->nombre?>
                                    <input type="hidden"
                                           name="horarios[<?php echo $d ?>][dia]"
                                           id="dia<?php echo $d ?>"
                                           value="<?php echo $d ?>"
                                           class="status" />
                                </th>
                                <td>
                                    <input type="text" size="5" maxlenght="5"
                                           name="horarios[<?php echo $d ?>][entrada]"
                                           id="entrada<?php echo $d ?>"
                                           value="<?php echo substr($horario->inicio,0,5); ?>"
                                           class="hora"/>
                                </td>
                                <td>
                                    <input type="text" size="5" maxlenght="5"
                                            name="horarios[<?php echo $d ?>][salida]"
                                            id="salida<?php echo $d ?>"
                                            value="<?php echo substr($horario->fin,0,5); ?>"
                                            class="hora"/>
                                </td>
                                <td>
                                    <select name="horarios[<?php echo $d ?>][aula]"
                                            id="aula<?php echo $d ?>"
                                            class="aula">
                                        <option></option>
                                        <?php foreach($aulas as $aula){?>
                                        <option value="<?php echo $aula->id?>"
                                            <?php if($horario->aulas_id == $aula->id){?>selected="selected"<?php } ?>>
                                                <?php echo $aula->clave?>
                                        </option>
                                        <?php } ?>
                                    </select>
                                </td>
                                <td>
                                    <img id="spinner<?php echo $d?>" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
                                    <div id="check<?php echo $d?>" class="check">
                                        <input type="hidden"
                                           name="horarios[<?php echo $d ?>][valido]"
                                           id="valido<?php echo $d ?>"
                                           value="0"
                                           class="status" />
                                       <span id="status<?php echo $d?>">-</span>
                                    </div>
                                </td>
                            </tr>
                            <?php } ?>
                        </table>
                        <br />
                    </fieldset>
                    <div class="separador"></div>
                    <div id="botones">
                        <input type="button" id="aceptar" value="Editar">
                        <input type="button" id="cancelar" value="Cancelar">

                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />La informaci&oacute;n del curso se agreg&oacute; correctamente</p>
            <?php  break; ?>
            <?php case 'conflicto':
            ?>
                <div class="error"><br/>
                    <?php echo $error ?>
                </div>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error"><br />Ha ocurrido un error al intentar agregar el curso<br/>
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>