<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Eliminar curso de <?php if($curso->id!='')echo $curso->verGrupo()?></h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path . 'cursos/index/' . $grp?>">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>cursos/eliminar/" id="frm_eliminar" method="post">
                    <input type="hidden" name="id" id="id" value="<?php echo $curso->id ?>" />
                    <p class="error">
                        Se dispone a eliminar toda la informaci&oacute;n del curso: <br />
                        <?php echo $curso->verGrupo() ?><br />
                        <?php echo $curso->verMateriaNombre() ?><br />
                        <?php echo $curso->verProfesor() ?><br />
                        <strong>&iquest;Desea continuar?</strong>
                    </p>
                    <div id="botones">
                        <input type="button" id="aceptar" value="Aceptar">
                        <input type="button" id="cancelar" value="Cancelar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El curso se elimin&oacute; correctamente.</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error">Ha ocurrido un error al intentar eliminar el curso.<br />
                <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>