<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Configuraci&oacute;n</h1>
        <p class="msj">
            <br />
            Importar Fotografias al Sistema.
        </p>
        <ul class="opciones">
            <li>
                <a href="<?php echo $path . 'importar/fotos/alumnos/' ?>">
                    Alumnos
                </a>
            </li>
            <li>
                <a href="<?php echo $path . 'importar/fotos/profesores/' ?>">
                    Profesores
                </a>
            </li>
        </ul>
    </div>
</div>