<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
	<?php if($option!="error"){ ?>
		<h1>Editar opciones avanzadas</h1>
		<h2>Inicia el <?php echo Utils::fecha_espanol(substr($periodo->inicio,0,10)); ?> a las <?php echo substr($periodo->inicio,10,6); ?></h2>
		<h2>Finaliza el <?php echo Utils::fecha_espanol(substr($periodo->fin,0,10)); ?> a las <?php echo substr($periodo->fin,10,6); ?></h2>
		<h2><?php echo ($periodo->activo==1? "Activo" : "Inactivo"); ?></h2>

		<div id="options-bar">
			<div id="options">
			<?php if($option!="error"){ ?>
				<a href="<?php echo $path ?>optativas/index/<?php echo $periodo_id; ?>">Volver a configuracion
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			<?php } ?>
			</div>
		</div>
		<?php } ?>
		<?php switch($option) {
			case 'exito': ?>
				<p class="info"><br />Opciones avanzadas editadas con exito.</p>
			<?php  break; ?>

			<?php case 'error':
				  default:
			?>
				<p class="error"><br />Ha ocurrido un error al modificar las opciones avanzadas.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>