<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Configurar TAES</h1>
		<?php if($option!="error"){ ?>
		<h2>Inicia el <?php echo Utils::fecha_espanol(substr($periodo->inicio,0,10)); ?> a las <?php echo substr($periodo->inicio,10,6); ?></h2>
		<h2>Finaliza el <?php echo Utils::fecha_espanol(substr($periodo->fin,0,10)); ?> a las <?php echo substr($periodo->fin,10,6); ?></h2>
		<h2><?php echo ($periodo->activo==1? "Activo" : "Inactivo"); ?></h2>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>optativas/index/<?php echo $periodo->id; ?>">Volver a optativas
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php } ?>

		<?php switch($option) {
				case 'vista': ?>
					<?php
						if(count($trayectorias)>0){
					 ?>
					<table>
						<tr>
						<th>Trayectoria</th><th>Cupos</th><th>Inscritos</th>
						</tr>
						<?php
						 $i = 0;
						 $tcupos = 0;
						 $tinscritos = 0;
						 foreach($trayectorias as $trayectoria ){
						 	 ?>
							<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
								<td>
								<a href="<?php echo $path; ?>optativas/trayectoria/<?php echo $trayectoria->id; ?>">
								<?php echo $trayectoria->nombre; ?>
								<br/>
								<span class="sub"><?php echo $trayectoria->verTurno(); ?><span>
								</a>
								</td>
								<td style="text-align: center">
									   		<?php $tcupos+=$trayectoria->cupos; echo $trayectoria->cupos; ?>
								</td>
								<td style="text-align: center">
									<?php $tinscritos+=$trayectoria->inscritos; echo $trayectoria->inscritos; ?>
								</td>
							</tr>
						<?php
							$i++;
						} ?>

						<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
								<td>
									Total
								</td>
								<td style="text-align: center">
									   		<?php echo $tcupos; ?>
								</td>
								<td style="text-align: center">
									<?php echo $tinscritos; ?>
								</td>
							</tr>

					</table>
					<div class="divisor"></div>
					<?php }else{ ?>
						<p class="error">
						<br />No se han cargado las trayectorias especializantes <br />

						</p>

					<?php } ?>

			<?php  break; ?>
		<?php case 'error':
				  default:
			?>
				<p class="error"><br />Ha ocurrido un error en el modulo optativas.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>