<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar periodo para el ciclo <?php echo $ciclo->numero; ?></h1>
		<?php if($option!="error"){ ?>
		<h2>Inicia el <?php echo Utils::fecha_espanol(substr($periodo->inicio,0,10)); ?> a las <?php echo substr($periodo->inicio,10,6); ?></h2>
		<h2>Finaliza el <?php echo Utils::fecha_espanol(substr($periodo->fin,0,10)); ?> a las <?php echo substr($periodo->fin,10,6); ?></h2>
		<h2><?php echo ($periodo->activo==1? "Activo" : "Inactivo"); ?></h2>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>periodos">Volver a periodos
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php } ?>
		<?php switch($option) {
				case 'captura': ?>
				<?php if(count($ciclos)>0){ ?>
				<form action="<?php echo $path ?>periodos/editar" id="frm_agregar" method="post">
					<fieldset>
						<legend>Datos</legend>
						<label for="ciclos_id">Ciclo</label><br />
						<select name="ciclos_id" id="ciclos_id">
							<option></option>
							<?php foreach($ciclos as $c){ ?>
							<option value="<?php echo $c->id; ?>" <?php if($c->id==$ciclo->id){ ?> selected="selected" <?php } ?>><?php echo $c->numero; ?></option>
							<?php } ?>
						</select>
						<br />
						<input type="hidden" name="id" id="id" value="<?php echo $periodo->id; ?>" />
						<label for="inicio">Inicio</label><br />
						<input type="text" name="inicio" id="inicio" size="16" maxlength="16" value="<?php echo $inicio; ?>" />
						<img id="calendario" src="<?php echo $path ?>public/img/sp5/calendario.png" />
						<br />
						<label for="fin">Fin</label><br />
						<input type="text" name="fin" id="fin" size="16" maxlength="16" value="<?php echo $fin; ?>" />
						<img id="calendario2" src="<?php echo $path ?>public/img/sp5/calendario.png" />
						<br />
						<label for="activo">Activo</label><br />
						<input type="checkbox" name="activo" value="1" <?php if($periodo->activo==1){ ?> checked="checked" <?php } ?>/>
					</fieldset>
					<div></div>
					<div id="botones">
						<input type="button" id="aceptar" value="Editar">
						<input type="button" id="cancelar" value="Cancelar">

					</div>
				</form>
				<?php }else{ ?>
					<p class="info"><br />Todos los ciclos ya cuentan con el periodo de inscripcion.</p>
				<?php } ?>
			<?php  break; ?>
			<?php case 'exito':
			?>
				<p class="info"><br />El periodo se edito correctamente.</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error"><br />Ha ocurrido al intentar editar el periodo.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>