<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Eliminar periodo</h1>
		<?php if($option!="error"){ ?>
		<h2>Inicia el <?php echo Utils::fecha_espanol(substr($periodo->inicio,0,10)); ?> a las <?php echo substr($periodo->inicio,10,6); ?></h2>
		<h2>Finaliza el <?php echo Utils::fecha_espanol(substr($periodo->fin,0,10)); ?> a las <?php echo substr($periodo->fin,10,6); ?></h2>
		<h2><?php echo ($periodo->activo==1? "Activo" : "Inactivo"); ?></h2>

		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>periodos">Volver a periodos
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php } ?>
		<?php switch($option) {
				case 'captura': ?>
					<form action="<?php echo $path ?>periodos/eliminar/" id="frm_eliminar" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $periodo->id ?>" />
					<p class="error">
						Se dispone a eliminar toda la informaci&oacute;n del periodo para el ciclo <span style="font-weight:bold;"><?php echo $periodo->numero?></span>.<br/>
						Se eliminaran los bloques,cursos y alumnos asignados al periodo.
						<br />
						<strong>&iquest;Desea continuar?</strong>
					</p>
					<div id="botones">
						<input type="button" id="aceptar" value="Aceptar">
						<input type="button" id="cancelar" value="Cancelar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito':
			?>
				<p class="info"><br />El periodo se elimino correctamente.</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error"><br />Ha ocurrido un error al eliminar el periodo.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>