<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Agregar tipo de personal</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>tipopersonal">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>tipopersonal/agregar" id="frm_agregar" method="post" enctype="multipart/form-data">
                    </fieldset>
                    <fieldset>
                        <legend>Tipo Personal</legend>
                        <label for="nombre">Nombre</label><br />
                        <input type="text" name="nombre" id="nombre" size="30" maxlength="50" /><br />
                        <br />
                    </fieldset>
                    <div id="botones">
                        <input type="button" id="cancelar" value="Cancelar">
                        <input type="button" id="agregar" value="Agregar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El tipo de personal se agreg&oacute; correctamente</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error"><br />Ha ocurrido un error al intentar agregar el tipo de personal.<br />
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>