<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar tipo de personal</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>tipopersonal">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) {
				case 'captura': ?>
				<form action="<?php echo $path ?>tipopersonal/editar" id="frm_editar" method="post" enctype="multipart/form-data">
					</fieldset>
					<fieldset>
						<legend>Tipo Personal</legend>
						<input type="hidden" name="id" id="id" value="<?php echo $personal->id; ?>" /><br />
						<label for="nombre">Nombre</label><br />
						<input type="text" name="nombre" id="nombre" size="30" maxlength="50" value="<?php echo $personal->nombre; ?>" /><br />
						<br />
					</fieldset>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="editar" value="Editar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El tipo de personal se edito correctamente</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error"><br />Ha ocurrido un error al intentar editar el tipo de personal.<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>