<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Datos del personal <?php echo $personal->codigo?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>personal">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
				<?php if($personal->id != ''){?>
					<?php if($acl['editar']){ ?>
		 			 / <a href="<?php echo $path . 'personal/editar/' . $personal->id?>"
					   alt="Editar datos del personal" title="Editar datos del personal">
					   Editar
					   <img src="<?php echo $path?>public/img/sp5/editar.png" />
					</a>
					<?php } ?>
					<?php if($acl['eliminar']){ ?>
					 / <a href="<?php echo $path . 'personal/eliminar/' . $personal->id?>"
					   alt="Eliminar toda la informacion del personal" title="Eliminar toda la informacion del personal">
					   Eliminar
					   <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
					</a>
					<?php } ?>
				<?php }?>
			</div>
		</div>
		<?php if($personal->id != '') {?>
		<table>
			<tr>
				<th>Personal</th>
				<td><?php echo  $tipo->nombre; ?></td>
				<td rowspan="6">
					<?php if($personal->foto != ''){ ?>
						<img src="<?php echo $path . 'public/img/personal/' . $personal->foto . '?d=' . time() ?>" class="ficha"/>
					<?php }else{ ?>
						<img src="<?php echo $path ?>public/img/sp5/persona.png" class="ficha"/>
					<?php }?>
				</td>
			</tr>

			<tr>
			<th>Nombre</th>
			<td><?php echo  $personal->ap . ' ' .
								$personal->am. ', '.
								$personal->nombre  ?>
				</td>
			</tr>

			<tr>
				<th>RFC</th>
				<td><?php echo $personal->mail?></td>
			</tr>
			<tr>
				<th>CURP</th>
				<td><?php echo $personal->curp?></td>
			</tr>
			<tr>
				<th>Sexo</th>
				<td><?php echo $personal->sexo?></td>
			</tr>
			<tr>
				<th>Fecha de nacimiento</th>
				<td><?php echo $personal->fnacimiento?></td>
			</tr>
			<tr>
				<th>Domicilio</th>
				<td colspan="2"><?php echo $personal->domicilio?></td>
			</tr>
			<tr>
				<th>Tel&eacute;fono</th>
				<td colspan="2"><?php echo $personal->tel?></td>
			</tr>
			<tr>
				<th>Tel&eacute;fono m&oacute;vil</th>
				<td colspan="2"><?php echo $personal->cel?></td>
			</tr>
			<tr>
				<th>Correo Electr&oacute;nico</th>
				<td colspan="2">
					<a href="mailto:<?php echo $personal->mail?>" />
					<?php echo $personal->mail?>
					</a>
				</td>
			</tr>
		</table>
		<?php } else {?>
			<p class="error">
				<br />
			 	No existe informaci&oacute;n del personal seleccionado.
			</p>
		<?php } ?>
	</div>
</div>