<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Agregar articulo</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>reglamentos/ver/<?php echo $reglamento_id ?>">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) { 
                case 'captura': ?>
                <form action="<?php echo $path ?>articulos/agregar" id="frm_agregar" method="post">
                    <fieldset>
                        <legend>Articulo</legend>
                        <label for="numero">Numero</label><br />
                        <input type="text" name="numero" id="numero" size="30" maxlength="30" />
                        <img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
                        <div id="check" class="check"></div><br />
                        <label for="descripcion">Descripci&oacute;n</label>
                        <textarea name="descripcion" id="descripcion" cols=40 rows=6></textarea><br />
                        <input type="hidden" name="reglamento" id="reglamento" value="<?php echo $reglamento_id ?>" />
                        <input type="hidden" name="path" id="path" value="<?php echo $path ?>" />
                    </fieldset>
                    <div id="botones">
                        <input type="button" id="cancelar" value="Cancelar">
                        <input type="button" id="agregar" value="Agregar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El articulo se agreg&oacute; correctamente</p>
            <?php  break; ?>
            <?php case 'error': 
                  default: 
            ?>
                <p class="error"><br />Ha ocurrido un error al intentar agregar el articulo
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>