<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>
		Importar articulos
		<?php
			if($option=="confirma"){
		 ?>
		 <br/>Vista Previa
		 <?php } ?>
		</h1>
		<h2><?php echo $reglamento->nombre ?></h2>
		<div id="options-bar">
			<div id="options">

                 <a href="<?php echo $path ?>reglamentos"> Volver a reglamentos
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>

			</div>
		</div>
		<?php switch($option){
			case "captura": ?>
		<form id="frm_agregar" enctype="multipart/form-data" method="post" action="importar">
		<fieldset>
		<legend>Archivo</legend>
		<input type="hidden" name="id_reg" value="<?php echo $reglamento->id; ?>" />
		<input id="archivo" name="archivo" type="file" /> <input type="submit" value="Enviar" />
		</fieldset>
		</form>

		<p class="tip">
		<br/>
		El importador soporta archivos de los siguientes formatos:
		CSV,XLS.
		<br/>
		El orden de los campos debera ser el siguiente:
		<br/>
		NUMERO DE ARTICULO,DESCRIPCION.
		<br/>
		</p>
		<?php
				break;
			case "confirma":
			$max=10;
			$rs=count($importar->registros);
			if($rs>0){
		?>
		<form id="frm_agregar" enctype="multipart/form-data" method="post" action="importar">
					<fieldset>
					<legend>Archivo</legend>
					<p>
					Existe<?php echo ($rs == 1 ? '' : 'n'); ?> <?php echo $rs; ?> registro<?php echo ($rs == 1 ? '' : 's'); ?>.
					¿Desea importarlos?</p>
					<input type="hidden" name="id_file" value="<?php echo $idFile; ?>" />
					<input type="hidden" name="id_reg" value="<?php echo $reglamento; ?>" />
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="submit" id="agregar" value="Importar">
					</div>
					</fieldset>
		</form>
		<?php if(count($importar->registros)>20){?>
		<h3>Solo se muestran los primeros <?php echo $max; ?> registros para corroborar las columnas con los datos.</h3>
		<?php } ?>
		<table >
		<tr>
		<?php foreach($importar->columnas as $col ){
			if($col!="*"){
			?>
		<th><?php echo utf8_encode($col); ?></th>
		<?php
			}
		 } ?>
		</tr>
		<?php
		$i = 0;
		$r=0;
		

		foreach($importar->registros as $registro){
		if($r<$max){
		?>
		<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
		<?php for($c=0;$c<count($registro);$c++){

			$celda=$registro[$c];

			 ?>
		<td style="text-align:center;" ><?php echo ((trim($celda)==""? '_' :	 $celda)); ?></td>
		<?php

		 } ?>
		</tr>
		<?php
		$i++;
		$r++;
		}else{
			break;
		}
		} ?>
		</table>

		<?php }else{ ?>
			<p class="error"><br/>No existe ningun registro en el archivo. </p>
			<?php } ?>
		<?php
				break;
			?>
		<?php
				break;
			case "exito": //echo count($importar->registros); echo $tutor."-".$grupo."-".$nombre;// echo "--- ".count($importar->columnas)."==".count($importar->registros[0]);var_dump($datos);
			 //var_dump($datos);
			  ?>
			<p class="info"><br/><?php echo $datos["m"][0]; ?></p>

			<?php $w=$datos["w"];
			if(count($w)>0){
				?>
				<h3>Warning<?php echo (count($w) != 1 ? 's' : ''); ?></h3>
				<table>
				<tr><th><?php echo count($w); ?> warning<?php echo (count($w) != 1 ? 's' : ''); ?></th></tr>
				<?php
				$i=0;
				 foreach($w as $r){ ?>
				<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>"><td><?php echo $r; ?></td></tr>
				<?php
					$i++;
				} ?>
				</table>
			<?php

			}
			 ?>

			<?php $e=$datos["e"];
			if(count($e)>0){
				?>
				<h3>Error<?php echo (count($e) != 1 ? 'es' : ''); ?></h3>
				<table>
				<tr><th><?php echo count($e); ?> error<?php echo (count($e) != 1 ? 'es' : ''); ?></th></tr>
				<?php
				$i=0;
				 foreach($e as $r){ ?>
				<tr  class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>"><td><?php echo $r; ?></td></tr>
				<?php
					$i++;
				} ?>
				</table>
			<?php

			}
			 ?>

			<?php
			break;
			case "error":
		?>
		<p class="error"><br /><?php echo $error; ?></p>
		<?php
				break;
			?>

		<?php } ?>

	</div>
</div>