<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Articulo <?php echo $articulo->numero?></h1>
        <?php switch($option) {
                case 'vista': ?>
                <div id="options-bar">
                    <div id="options">
                        <a href="<?php echo $path ?>reglamentos">Volver a reglamentos
                            <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                        </a>
                        <?php /*?>

                        <?php if($acl['articulos']['editar']){ ?>
                          / <a href="<?php echo $path . 'alumnos/editar/' . $alumno->id ?>"
                           alt="Editar datos del alumno" title="Editar datos del alumno">
                           Editar
                           <img src="<?php echo $path?>public/img/sp5/editar.png" />
                        </a>
                        <?php } ?>
                        <?php if($acl['aarticulos']['eliminar']){ ?>
                         / <a href="<?php echo $path . 'alumnos/eliminar/' . $alumno->id ?>"
                           alt="Eliminar toda la informacion del alumno" title="Eliminar toda la informacion del alumno">
                           Eliminar
                           <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
                        </a>
                        <?php } ?>
                        <?php */?>
                    </div>
                </div>
                <?php /*?>
                <table>
                    <tr>
                        <th>Articulo</th>
                        <td><?php echo  $articulo->numero?>
                        </td>
                    </tr>
                    <tr>
                        <th>Descripci&oacute;n</th>
                        <td><?php echo $articulo->descripcion ?></td>
                    </tr>
                </table>
                <?php */?>
                <h1>Articulo <?php echo $articulo->numero?></h1>
                <br ><br >
                <p><?php echo $articulo->descripcion?></p>
        <?php break; ?>
        <?php case 'error':
              default:
        ?>
                <div id="options-bar">
                    <div id="options">
                        <a href="<?php echo $path ?>reglamentos">Volver a reglamentos
                            <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                        </a>
                    </div>
                </div>
                <p class="error">
                    <br />
                     <?php echo $error ?>
                </p>
        <?php break; ?>
        <?php } ?>
    </div>
</div>