<div id="primary">
    <div class="content">
        <h1>
            Historial
        </h1>
        <h2>
            <?php echo $registros;?>
            Registro<?php echo ($registros == 1 ? '' : 's') ?>
            <?php if($busqueda->condicion() != '') {?><div class="filter-lab">Contenido filtrado</div><?php }?>

        </h2>
        <div id="options-bar">
            <div id="options">
            <?php if($acl['buscar']){ ?>
                <a href="" id="aSearch" title="Buscar" alt="Buscar">
                    Buscar
                    <img src="<?php echo $path?>public/img/sp5/buscar.png"/>
                </a>
                /
                <?php } ?>
                <?php if($acl['exportar']){ ?>
                <a href="<?php echo $path . 'historial/exportar/' ?>" title="Exportar historial" alt="Exportar historial">
                    Exportar
                    <img src="<?php echo $path?>public/img/sp5/excel.png"/>
                </a>
                /
                <?php } ?>
                <a href="#" id="cicloBtn" title="Cambiar de ciclo escolar" alt="Cambiar de ciclo escolar">
                    Ciclo:
                </a>
                <div id="cicloActual"><?php echo $ciclo->numero?></div>
                <div id="cicloSel" style="display:none">
                    <form id="frm_ciclo" method="post" action="<?php echo $path ?>sistema/seleccionar">
                    <fieldset>
                        <input type="hidden" name="controlador" value="<?php echo $controlador ?>" />
                        <input type="hidden" name="accion" value="<?php echo $accion ?>" />
                        <select name="ciclo" id="cicloSelect">
                            <?php foreach($ciclos as $ccl){?>
                            <option value="<?php echo $ccl->id?>"
                                    <?php if($ccl->id == $ciclo->id){ ?>selected="selected"<?php } ?>>
                                    <?php echo $ccl->numero?>
                            </option>
                            <?php } ?>
                        </select>
                    </fieldset>
                    </form>
                </div>

            </div>
            <?php if($acl['buscar']){ ?>
            <div id="search" <?php if($busqueda->condicion() == ''){?> style="display:none" <?php } ?>>
                <form action="<?php echo $path ?>historial" method="post" id="frm_search">
                    <fieldset>
                    <label for="usuario">Usuario</label>
                        <input type="text" name="usuario" id="usuario" value="<?php echo $busqueda->campo('usuario') ?>" size="12" maxlength="12" />
                    <label for="descripcion">Descripcion</label>
                        <input type="text" name="descripcion" id="descripcion" value="<?php echo $busqueda->campo('descripcion') ?>" size="12" maxlength="12" />
                    <label for="controlador">Controlador</label>
                        <select name="controlador" id="controlador">
                        <option></option>
                        <?php foreach($controladores as $c){ ?>
                        <option value="<?php echo $c; ?>" <?php if($busqueda->campo('controlador')==$c)echo 'selected="selected"'; ?>><?php echo $c; ?></option>
                        <?php } ?>
                        </select>
                    <label for="accion">Accion</label>
                        <input type="text" name="accion" id="accion" value="<?php echo $busqueda->campo('accion') ?>" size="12" maxlength="12" />
                    <label for="saved_at">Fecha</label>
                        <input type="text" name="saved_at" id="saved_at" value="<?php echo $busqueda->campo('saved_at') ?>" size="10" maxlength="10" />
                        <br/><br/>
                        <input type="submit" id="btn_submit" value="Filtrar" />
                        <input type="reset" id="reset" value="Quitar filtros" />
                    </fieldset>
                </form>
            </div>
            <?php  } ?>

        </div>
        <?php if($registros > 0){ ?>
            <table>
            <tr><th>Fecha</th><th>Registro</th><th>Descripción</th><tr>
            <?php
             $i=0;
             foreach($historial as $h){ ?>
            <tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
            <td style="text-align:center;"><span class="sub"><?php

             echo Utils::convierteFecha(substr($h->saved_at,0,10)); ?>
             </span><br/>
             <span style="color: rgb(119, 119, 119);" class="sub">
             <?php echo substr($h->saved_at,10); ?>
             </span>
             </td>
            <td style="text-align:left;">
             <span class="sub">
            <?php echo $h->usuario; ?>
            </span>
            <br/>
             <span style="color: rgb(119, 119, 119);" class="sub">
            <?php echo $h->controlador; ?>/<?php echo $h->accion; ?>
            </span>
            </td>
            <td>
            <?php if($acl['ver']){ ?>
            <a href="<?php echo $path . 'historial/ver/' . $h->id?>"
                    alt="Ver registro" title="Ver registro">
                    <?php echo $h->descripcion; ?>
            </a>
            <?php }else{ ?>
                <?php echo $h->descripcion; ?>
            <?php } ?>
            </td>

            <tr>
            <?php
                $i++;
             } ?>
            <table>
        <?php } else { ?>
                <p class="info"><br />No hay registros que mostrar...</p>
        <?php } ?>
        <div id="pages">
        <?php foreach($paginador->botones() as $boton){ ?>
                 <a  href="<?php echo $path . $boton->url() ?>"
                    title="Ir a la p&aacute;gina <?php echo $boton->titulo() ?>"
                    class="<?php echo $boton->estilo() ?>">
                    <?php echo $boton->etiqueta() ?>
                </a>
            <?php }?>
        </div>
    </div>
</div>