<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Eliminar profesor <?php echo $profesor->codigo?></h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>profesores">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>profesores/eliminar/" id="frm_eliminar" method="post">
                    <input type="hidden" name="id" id="id" value="<?php echo $profesor->id ?>" />
                    <p class="error">
                        Se dispone a eliminar toda la informaci&oacute;n del profesor
                        <?php echo $profesor->codigo?>,
                        <?php echo $profesor->nombre .' ' . $profesor->ap . ' ' . $profesor->am?>
                        <br />
                        Los cursos donde el profesor sea el encargado seran cambiados al profesor staff.
                        <strong>&iquest;Desea continuar?</strong>
                    </p>
                    <div id="botones">
                        <input type="button" id="aceptar" value="Aceptar">
                        <input type="button" id="cancelar" value="Cancelar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El profesor se elimin&oacute; correctamente.</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error">Ha ocurrido un error al intentar eliminar el profesor.<br />
                <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>