<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Datos del profesor <?php echo $profesor->codigo?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>profesores">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
				<?php if($profesor->id != ''){?>
					<?php if($acl['password']){ ?>
		 			 / <a href="<?php echo $path . 'profesores/password/' . $profesor->id?>"
							   	alt="Cambiar el password del profesor" title="Cambiar password del profesor">
							 Password
							   	<img src="<?php echo $path?>public/img/sp5/pass.png" />

							</a>
					<?php } ?>
					<?php if($acl['editar']){ ?>
		 			 / <a href="<?php echo $path . 'profesores/editar/' . $profesor->id?>"
					   alt="Editar datos del profesor" title="Editar datos del profesor">
					   Editar
					   <img src="<?php echo $path?>public/img/sp5/editar.png" />
					</a>
					<?php } ?>
					<?php if($acl['eliminar']){ ?>
					 / <a href="<?php echo $path . 'profesores/eliminar/' . $profesor->id?>"
					   alt="Eliminar toda la informacion del profesor" title="Eliminar toda la informacion del profesor">
					   Eliminar
					   <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
					</a>
					<?php } ?>
					<?php if($acl['horario']){ ?>
					 / <a href="<?php echo $path . 'profesores/horario/' . $profesor->id?>"
					   alt="Horario del profesor" title="Horario del profesor">
					   Horario
					   <img src="<?php echo $path?>public/img/sp5/reloj.png" />
					</a>
					<?php } ?>
				<?php }?>
			</div>
		</div>
		<?php if($profesor->id != '') {?>
		<table>
			<tr>
				<th>Nombre</th>
				<td><?php echo  $profesor->ap . ' ' .
								$profesor->am. ', '.
								$profesor->nombre  ?>
				</td>
				<td rowspan="5">
					<?php if($profesor->foto != ''){ ?>
						<img src="<?php echo $path . 'public/img/profesores/' . $profesor->foto . '?d=' . time() ?>" class="ficha"/>
					<?php }else{ ?>
						<img src="<?php echo $path ?>public/img/sp5/persona.png" class="ficha"/>
					<?php }?>
				</td>
			</tr>
			</tr>
			<tr>
				<th>RFC</th>
				<td><?php echo $profesor->mail?></td>
			</tr>
			<tr>
				<th>CURP</th>
				<td><?php echo $profesor->curp?></td>
			</tr>
			<tr>
				<th>Sexo</th>
				<td><?php echo $profesor->sexo?></td>
			</tr>
			<tr>
				<th>Fecha de nacimiento</th>
				<td><?php echo $profesor->fnacimiento?></td>
			</tr>
			<tr>
				<th>Domicilio</th>
				<td colspan="2"><?php echo $profesor->domicilio?></td>
			</tr>
			<tr>
				<th>Tel&eacute;fono</th>
				<td colspan="2"><?php echo $profesor->tel?></td>
			</tr>
			<tr>
				<th>Tel&eacute;fono m&oacute;vil</th>
				<td colspan="2"><?php echo $profesor->cel?></td>
			</tr>
			<tr>
				<th>Correo Electr&oacute;nico</th>
				<td colspan="2">
					<a href="mailto:<?php echo $profesor->mail?>" />
					<?php echo $profesor->mail?>
					</a>
				</td>
			</tr>
		</table>
		<?php } else {?>
			<p class="error">
				<br />
			 	No existe informaci&oacute;n del profesor seleccionado.
			</p>
		<?php } ?>
	</div>
</div>