<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Agregar reglamento</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>reglamentos">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) { 
                case 'captura': ?>
                <form action="<?php echo $path ?>reglamentos/agregar" id="frm_agregar" method="post">
                    <fieldset>
                        <legend>Reglamento</legend>
                        <label for="nombre">Nombre</label><br />
                        <input type="text" name="nombre" id="nombre" size="30" maxlength="255" /><br />
                        <img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
                        <div id="check" class="check"></div><br />
                        <label for="descripcion">Descripci&oacute;n</label>
                        <textarea name="descripcion" id="descripcion" cols=40 rows=6></textarea><br />
                    </fieldset>
                    <div></div>
                    <fieldset>
                        <legend>Vigencia</legend>
                        <label for="inicio">Inicio</label><br />
                        <input type="text" name="inicio" id="inicio" size="10" maxlength="10" readonly />
                        <a id="calendario"><img src="<?php echo $path ?>/public/img/sp5/calendario.png" /></a><br />
                        <label for="fin">Fin</label><br />
                        <input type="text" name="fin" id="fin" size="10" maxlength="10" readonly />
                        <a id="calendario2"><img src="<?php echo $path ?>/public/img/sp5/calendario.png" /></a><br />
                    </fieldset>
                    <div id="botones">
                        <input type="button" id="cancelar" value="Cancelar">
                        <input type="button" id="agregar" value="Agregar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El reglamento se agreg&oacute; correctamente</p>
            <?php  break; ?>
            <?php case 'error': 
                  default: 
            ?>
                <p class="error"><br />Ha ocurrido un error al intentar agregar el reglamento
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>