<div id="primary">
	<div class="content">
		<h1>
			<?php echo $registros;?>
			Reglamento<?php echo ($registros == 1 ? '' : 's') ?>
			<?php if($busqueda->condicion() != '') {?><div class="filter-lab">Contenido filtrado</div><?php }?>
		</h1>
		<div id="options-bar">
			<div id="options">
			<?php if($acl['buscar']){ ?>
				<a href="" id="aSearch" title="Buscar" alt="Buscar">
					Buscar
					<img src="<?php echo $path?>public/img/sp5/buscar.png"/>
				</a>
				<?php } ?>
				 <?php if($acl['agregar']){ ?>
				/
				<a href="<?php echo $path ?>reglamentos/agregar" title="Agregar reglamento" alt="Agregar reglamento">
					Agregar reglamento
					<img src="<?php echo $path?>public/img/sp5/nuevo.png"/>
				</a>
				<?php } ?>
				/<a href="<?php echo $path ?>amonestaciones"> Volver a amonestaciones
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
			<?php if($acl['buscar']){ ?>
			<div id="search" <?php if($busqueda->condicion() == ''){?> style="display:none" <?php } ?>>
				<form action="<?php echo $path ?>reglamentos" method="post" id="frm_search">
					<fieldset>
						<label for="nombre">Nombre</label>
						<input type="text" name="nombre" id="nombre" value="<?php echo $busqueda->campo('nombre') ?>" size="20" maxlength="255" />
						<label for="nombre">Descripci&oacute;n</label>
						<input type="text" name="descripcion" id="descripcion" value="<?php echo $busqueda->campo('descripcion') ?>" size="20" maxlength="255" />
						<input type="submit" id="btn_submit" value="Filtrar" />
						<input type="reset" id="reset" value="Quitar filtros" />
					</fieldset>
				</form>
			</div>
			<?php } ?>
		</div>
		<?php if($registros > 0){ ?>
				<table>
					<tr>
						<th>Nombre</th>
						<th>Descripci&oacute;n</th>
						<th>Vigencia</th>
						<?php if($acl['editar'] || $acl['eliminar'] || $acl_art['agregar']){ ?>
						<th>Opciones</th>
						<?php } ?>
					</tr>
					<?php
						$i = 0;
						foreach($reglamentos as $reglamento){
							$reg_art = new Reglamento();
							$articulos = $reg_art->count_by_sql('SELECT COUNT(*) FROM reglamento WHERE reglamentos_id = '.$reglamento->id);
					?>
					<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
						<td>
							<a href="<?php echo $path . 'reglamentos/ver/' . $reglamento->id?>"
								   alt="Ver datos del reglamento" title="Ver datos del reglamento">
									<?php echo $reglamento->nombre?>
									<br />
									<span class = "sub"><?php echo $articulos.' articulo'.( $articulos == 1 ? '' : 's') ?></span>
							</a>
						</td>
						<td>
							<?php echo (strlen($reglamento->descripcion) < 100 ? $reglamento->descripcion : substr($reglamento->descripcion,0,100).'...') ?>
						</td>
						<td>
							<?php if($reglamento->inicio != ''){ ?>
								<span class = "true"><?php echo ($reglamento->inicio != '0000-00-00' ? Utils :: fecha_mix($reglamento->inicio) : '  -  ') ?></span>
							<?php }else{ ?>
								<span class = "true"><?php echo '  -  '?></span>
							<?php } ?>
							<br />
							<?php if($reglamento->fin != ''){ ?>
								<span class = "false"><?php echo ($reglamento->fin != '0000-00-00' ? Utils :: fecha_mix($reglamento->fin) : '  -  ') ?></span>
							<?php }else{ ?>
								<span class = "false"><?php echo '  -  '?></span>
							<?php } ?>
						</td>
						<?php if($acl['editar'] || $acl['eliminar']){ ?>
						<td>
							<?php if($acl['editar']){ ?>
							<a href="<?php echo $path . 'reglamentos/editar/' . $reglamento->id?>"
							   alt="Editar datos del reglamento" title="Editar datos del reglamento">
							   <img src="<?php echo $path?>public/img/sp5/editar.png" />
							</a>
							<?php } ?>
							<?php if($acl['eliminar']){ ?>
							<a href="<?php echo $path . 'reglamentos/eliminar/' . $reglamento->id?>"
							   alt="Eliminar toda la informacion del reglamento" title="Eliminar toda la informacion del reglamento">
							   <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
							</a>
							<?php } ?>	
						</td>
						<?php } ?>
					</tr>
					<?php
						$i++;
					}
					?>
				</table>
		<?php } else { ?>
				<p class="info"><br />No hay registros que mostrar...</p>
		<?php } ?>
		<div id="pages">
			<?php foreach($paginador->botones() as $boton){ ?>
				 <a  href="<?php echo $path . $boton->url() ?>"
					title="Ir a la p&aacute;gina <?php echo $boton->titulo() ?>"
					class="<?php echo $boton->estilo() ?>">
					<?php echo $boton->etiqueta() ?>
				</a>
			<?php }?>
		</div>
	</div>
</div>