<div id="primary">
    <div class="content">
        <h1>
            <?php echo $registros;?>
            Profesor<?php echo ($registros == 1 ? '' : 'es') ?>
            <?php if($busqueda->condicion() != '') {?><div class="filter-lab">Contenido filtrado</div><?php }?>
        </h1>
        <div id="options-bar">
            <div id="options">
            <?php if($acl['buscar']){ ?>
                <a href="" id="aSearch" title="Buscar" alt="Buscar">
                    Buscar
                    <img src="<?php echo $path?>public/img/sp5/buscar.png"/>
                </a>
                <?php } ?>
                <?php if($acl['exportar']){ ?>
                  /
                  <a href="<?php echo $path . 'profesores/exportar/' ?>" title="Exportar profesores" alt="Exportar profesores">
                    Exportar
                    <img src="<?php echo $path?>public/img/sp5/excel.png"/>
                </a>

                 <?php } ?>
                 <?php if($acl['agregar']){ ?>
                /
                <a href="<?php echo $path ?>profesores/agregar" title="Agregar profesor" alt="Agregar profesor">
                    Agregar profesor
                    <img src="<?php echo $path?>public/img/sp5/nuevo.png"/>
                </a>
                <?php } ?>
            </div>
            <?php if($acl['buscar']){ ?>
            <div id="search" <?php if($busqueda->condicion() == ''){?> style="display:none" <?php } ?>>
                <form action="<?php echo $path ?>profesores" method="post" id="frm_search">
                    <fieldset>
                        <label for="codigo">C&oacute;digo</label>
                        <input type="text" name="codigo" id="codigo" value="<?php echo $busqueda->campo('codigo') ?>" size="15" maxlength="12" />
                        <label for="nombre">Nombre</label>
                        <input type="text" name="nombre" id="nombre" value="<?php echo $busqueda->campo('nombre') ?>" size="20" maxlength="70" />
                        <label for="sexo">Sexo</label>
                        <select name="sexo" id="sexo">
                            <option></option>
                            <option value="H" <?php if($busqueda->campo('sexo') == 'H'){ ?>selected="selected"<?php } ?>>H</option>
                            <option value="M" <?php if($busqueda->campo('sexo') == 'M'){ ?>selected="selected"<?php } ?>>M</option>
                        </select>

                        <input type="submit" id="btn_submit" value="Filtrar" />
                        <input type="reset" id="reset" value="Quitar filtros" />
                    </fieldset>
                </form>
            </div>
            <?php } ?>
        </div>
        <?php if($registros > 0){ ?>
                <table>
                    <tr>
                        <th>Foto</th>
                        <th>Nombre</th>
                        <?php if($acl['editar'] || $acl['eliminar'] || $acl['password']){ ?>
                        <th>Opciones</th>
                        <?php } ?>
                    </tr>
                    <?php
                        $i = 0;
                        foreach($profesores as $profesor){
                    ?>
                    <tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
                        <td>
                            <a href="<?php echo $profesor->foto  ?>"
                               rel="lightbox[]"
                               title="<?php echo $profesor->ap . ' ' . $profesor->am . ' ' . $profesor->nombre ?>"
                               alt="<?php echo $profesor->ap . ' ' . $profesor->am . ' ' . $profesor->nombre ?>">
                                <img src="<?php echo $profesor->foto ?>" class="thumb"/>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $path . 'profesores/ver/' . $profesor->id?>"
                                   alt="Ver datos del profesor" title="Ver datos del profesor">
                                <span class="uc">
                                    <?php echo $profesor->ap . ' '  . $profesor->am . ', '?>
                                </span>
                                <?php echo $profesor->nombre    ?>
                                <br />
                                <span class="sub"><?php echo $profesor->codigo; ?></span>
                            </a>
                        </td>
                        <?php if($acl['editar'] || $acl['eliminar'] || $acl['password']){ ?>
                        <td>
                            <?php if(strToLower($profesor->codigo) != 'staff'){ ?>
                            <?php if($acl['editar']){ ?>
                            <a href="<?php echo $path . 'profesores/editar/' . $profesor->id?>"
                               alt="Editar datos del profesor" title="Editar datos del profesor">
                               <img src="<?php echo $path?>public/img/sp5/editar.png" />
                            </a>
                            <?php } ?>
                            <?php if($acl['eliminar']){ ?>
                            <a href="<?php echo $path . 'profesores/eliminar/' . $profesor->id?>"
                               alt="Eliminar toda la informacion del profesor" title="Eliminar toda la informacion del profesor">
                               <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
                            </a>
                            <?php } ?>
                            <?php if($acl['password']){ ?>
                            <a href="<?php echo $path . 'profesores/password/' . $profesor->id?>"
                                   alt="Cambiar el password del profesor" title="Cambiar password del profesor">
                                   <img src="<?php echo $path?>public/img/sp5/pass.png" />
                            </a>
                            <?php } ?>
                            <?php  } ?>
                        </td>
                        <?php } ?>
                    </tr>
                    <?php
                        $i++;
                    }
                    ?>
                </table>
        <?php } else { ?>
                <p class="info"><br />No hay registros que mostrar...</p>
        <?php } ?>
        <div id="pages">
            <?php foreach($paginador->botones() as $boton){ ?>
                 <a  href="<?php echo $path . $boton->url() ?>"
                    title="Ir a la p&aacute;gina <?php echo $boton->titulo() ?>"
                    class="<?php echo $boton->estilo() ?>">
                    <?php echo $boton->etiqueta() ?>
                </a>
            <?php }?>
        </div>
    </div>
</div>