<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Agregar aula</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>aulas">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) {
				case 'captura': ?>
				<form action="<?php echo $path ?>aulas/agregar" id="frm_agregar" method="post">
					<fieldset>
						<input type="hidden" name="KUMBIA_PATH" id="KUMBIA_PATH" value="<?php echo $path; ?>"/>
						<legend>Datos</legend>
						<label for="clave">Clave</label><br />
  						<input type="text" name="clave" id="clave" value="<?php echo $aula->clave; ?>" size="6" maxlength="6"/>	<img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
						<div id="check" class="check"></div>
						<br />
						<label for="nombre">Nombre</label><br />
  						<input type="text" name="nombre" id="nombre" value="<?php echo $aula->nombre; ?>" size="30" maxlength="30" /><br />
					</fieldset>
					<div id="botones">

						<input type="button" id="aceptar" value="Editar">
						<input type="button" id="cancelar" value="Cancelar">

					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />La informaci&oacute;n del aula se agreg&oacute; correctamente</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error"><br />Ha ocurrido un error al intentar agregar el aula
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>