<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Editar alumno</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>alumnos">Volver a alumnos
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>alumnos/editar" id="frm_editar" method="post" enctype="multipart/form-data">
                    <fieldset>
                        <legend>Personal</legend>
                        <input type="hidden" name="id" id="id" value="<?php echo $alumno->id ?>" />
                        <label for="codigo">Codigo</label><br />
                        <input 
                            type="text" 
                            name="codigo" 
                            id="codigo" 
                            maxlength="20" 
                            size="15" 
                            value="<?php echo $alumno->codigo ?>"/>
                        <img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
                        <div id="check" class="check"></div>
                        <br />
                        <label for="nombre">Nombre</label><br />
                        <input type="text" name="nombre" id="nombre" size="30" maxlength="30" value="<?php echo $alumno->nombre ?>" /><br />
                        <label for="ap">Apellido paterno</label><br />
                        <input type="text" name="ap" id="ap" size="20" maxlength="20" value="<?php echo $alumno->ap ?>" /><br />
                        <label for="am">Apellido materno</label><br />
                        <input type="text" name="am" id="am" size="20" maxlength="20" value="<?php echo $alumno->am ?>" /><br />
                        <label for="curp">CURP</label><br />
                        <input type="text" name="curp" id="curp" size="20" maxlength="20" value="<?php echo $alumno->curp ?>" />
                        <label><input type="radio" id="hombre" name="sexo" value="M" <?php if($alumno->sexo == 'M'){ ?>checked="checked"<?php }?>/> Mujer </label>
                        <label><input type="radio" id="mujer" name="sexo" value="H" <?php if($alumno->sexo == 'H'){ ?>checked="checked"<?php }?>/> Hombre </label><br />
                        <label for="fnacimiento">Fecha de nacimiento</label><br />
                        <input type="text" name="fnacimiento" id="fnacimiento" size="10" maxlength="10" value="<?php echo $alumno->fnacimiento() ?>" />
                        <a href="#" id="cal"><img src="<?php echo $path ?>/public/img/sp5/calendario.png" /></a><br />
                        <label for="foto">Foto</label><br />
                        <?php if($alumno->foto != ''){ ?>
                        <input type="hidden" id="cambiar" name="cambiarImagen" value="false" />
                        <div id="imagen" />
                            <br />
                            <img class="ficha"
                                 src="<?php echo KUMBIA_PATH . 'public/img/alumnos/' . $alumno->foto . '?d=' .time()?>"/>
                            <br />
                            <input type="button" id="iCambiar" value="Cambiar imagen" />
                        </div>
                        <div id="examinar" style="display:none">
                            <input type="file" id="foto" name="foto" />
                            <input type="button" id="iCancelar" value="Cancelar" />
                        </div>
                        <?php }else{ ?>
                                <input type="hidden" id="cambiar" name="cambiarImagen" value="true" />
                                <input type="file" id="foto" name="foto" />
                        <?php } ?>
                    </fieldset>
                    <div class="divisor"></div>
                    <fieldset>
                        <legend>Escolar</legend>
                        <label for="admision">Fecha de admisi&oacute;n</label><br />
                        <input type="text" name="admision" id="admision" size="10" maxlength="10" value="<?php echo $alumno->admision()?>"/>
                        <a id="cal2"><img src="<?php echo $path ?>/public/img/sp5/calendario.png" /></a><br />
                        <label for="situaciones_id">Situaci&oacute;n</label><br />
                        <select name="situaciones_id" id="situacion">
                            <option></option>
                            <?php foreach($situaciones as $situacion){ ?>
                            <option value="<?php echo $situacion->id?>"
                            <?php if($situacion->id == $alumno->situaciones_id){?> selected="selected"<?php } ?>>
                                <?php echo $situacion->nombre?>
                            </option>
                            <?php } ?>
                        </select><br/>
                        <label for="promedio">Promedio</label><br/>
                        <input type="text" name="promedio" id="promedio" size="10" maxlength="6" value="<?php echo $alumno->promedio; ?>" /><br />
                        <label for="aprobadas">Materias Aprobadas</label><br/>
                        <input type="text" name="aprobadas" id="aprobadas" size="10" maxlength="2" value="<?php echo $alumno->aprobadas; ?>" /><br />

                    </fieldset>
                    <div class="divisor"></div>
                    <?php if(false){ ?>
                    <fieldset>
                        <legend>Inscripci&oacute;n</legend>
                        <label for="grupo">Grupo</label><br />
                        <select name="grupos_id" id="grupo">
                            <option></option>
                            <option value="<?php echo $situacion->id?>">1&deg;A Matutino</option>
                            <option value="<?php echo $situacion->id?>">1&deg;B Matutino</option>
                            <option value="<?php echo $situacion->id?>">1&deg;C Matutino</option>
                            <option value="<?php echo $situacion->id?>">1&deg;D Matutino</option>
                        </select>
                        <br /><br />
                        <label for="cursos">Cursos</label><br />
                        <label><input type="checkbox" /> Lengua Espa&ntilde;ola </label><br />
                        <label><input type="checkbox" /> Matematicas </label><br />
                        <label><input type="checkbox" /> Logica </label><br />
                        <label><input type="checkbox" /> Lengua Extranjera </label><br />
                    </fieldset>
                    <div class="divisor"></div>
                    <?php } ?>
                    <fieldset>
                        <legend>Contacto</legend>
                        <label for="domicilio">Domicilio</label><br />
                        <input type="text" name="domicilio" id="domicilio" size="30" maxlength="60" value="<?php echo $alumno->domicilio ?>" /><br />
                        <label for="tel">Tel&eacute;fono</label><br />
                        <input type="text" name="tel" id="tel" size="20" maxlength="20" value="<?php echo $alumno->tel ?>" /><br />
                        <label for="tel">Tel&eacute;fono m&oacute;vil</label><br />
                        <input type="text" name="cel" id="cel" size="20" maxlength="20" value="<?php echo $alumno->cel ?>" /><br />
                        <label for="mail">Correo electr&oacute;nico</label><br />
                        <input type="text" name="mail" id="mail" size="30" maxlength="80" value="<?php echo $alumno->mail ?>" /><br />
                    </fieldset>
                    <div id="botones">
                        <input type="button" id="aceptar" value="Editar">
                        <input type="button" id="cancelar" value="Cancelar">

                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El alumno <strong><?php echo $alumno->codigo; ?> - <?php echo $alumno->ap." ".$alumno->am." ".$alumno->nombre; ?></strong> se edit&oacute; correctamente</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error"><br />
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>