<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Eliminar alumno</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>alumnos">Volver a alumnos
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>alumnos/eliminar/" id="frm_eliminar" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $alumno->id ?>" />
					<p class="error">
						Se dispone a eliminar toda la informaci&oacute;n del alumno 
						<?php echo $alumno->codigo?>,
						<?php echo $alumno->nombre .' ' . $alumno->ap . ' ' . $alumno->am?>
						<br />
						<strong>&iquest;Desea continuar?</strong>
					</p>
					<div id="botones">
						<input type="button" id="aceptar" value="Aceptar">
						<input type="button" id="cancelar" value="Cancelar">					
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El alumno se elimin&oacute; correctamente.</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error"><br />Ha ocurrido un error al intentar eliminar el alumno.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>