<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>
			<?php echo $registros;?>
			Alumno<?php echo ($registros == 1 ? '' : 's') ?>
			<?php if($busqueda->condicion() != '') {?><div class="filter-lab">Contenido filtrado</div><?php }?>
		</h1>
		<div id="options-bar">
			<div id="options">
			<?php if($acl['alumnos']['buscar']){?>
				<a href="" id="aSearch" title="Buscar" alt="Buscar">
					Buscar
					<img src="<?php echo $path?>public/img/sp5/buscar.png"/>
				</a>
				/
				<?php } ?>
				  <?php if($acl['alumnos']['exportar']){?>

                  <a href="<?php echo $path . 'alumnos/exportar/' ?>" title="Exportar alumnos" alt="Exportar alumnos">
                    Exportar
                    <img src="<?php echo $path?>public/img/sp5/excel.png"/>
                </a>
                /
                <?php } ?>

				<?php if($acl['alumnos']['agregar']){ ?>
				  <a href="<?php echo $path ?>alumnos/agregar" title="Agregar alumno" alt="Agregar alumno">
					Agregar alumno
					<img src="<?php echo $path?>public/img/sp5/nuevo.png"/>
				</a>
				/
				<?php } ?>
				<a href="#" id="cicloBtn" title="Cambiar de ciclo escolar" alt="Cambiar de ciclo escolar">
					Ciclo:
				</a>
				<div id="cicloActual"><?php echo $ciclo->numero?></div>
				<div id="cicloSel" style="display:none">
					<form id="frm_ciclo" method="post" action="<?php echo $path ?>sistema/seleccionar">
					<fieldset>
						<input type="hidden" name="controlador" value="<?php echo $controlador ?>" />
						<input type="hidden" name="accion" value="<?php echo $accion ?>" />
						<select name="ciclo" id="cicloSelect">
							<?php foreach($ciclos as $ccl){?>
							<option value="<?php echo $ccl->id?>"
									<?php if($ccl->id == $ciclo->id){ ?>selected="selected"<?php } ?>>
									<?php echo $ccl->numero?>
							</option>
							<?php } ?>
						</select>
					</fieldset>
					</form>
				</div>

			</div>
			<div id="search" <?php if($busqueda->condicion() == ''){?> style="display:none" <?php } ?>>
				<form action="<?php echo $path ?>alumnos" method="post" id="frm_search">
					<fieldset>
						<label for="codigo">C&oacute;digo</label>
						<input type="text" 
							name="codigo" 
							id="codigo" 
							size="20" 
							maxlength="20"
							value="<?php echo $busqueda->campo('codigo') ?>"  />
						<label for="nombre">Nombre</label>
						<input type="text" name="nombre" id="nombre" value="<?php echo $busqueda->campo('nombre') ?>" size="15" maxlength="70" />
						<label for="sexo">Sexo</label>
						<select name="sexo" id="sexo">
							<option></option>
							<option value="H" <?php if($busqueda->campo('sexo') == 'H'){ ?>selected="selected"<?php } ?>>H</option>
							<option value="M" <?php if($busqueda->campo('sexo') == 'M'){ ?>selected="selected"<?php } ?>>M</option>
						</select>
						<label for="grado">Grado</label>
						<select name="grado" id="grado">
							<option></option>
							<option value="1" <?php if($busqueda->campo('grado') == 1){ ?>selected="selected"<?php } ?>>1</option>
							<option value="2" <?php if($busqueda->campo('grado') == 2){ ?>selected="selected"<?php } ?>>2</option>
							<option value="3" <?php if($busqueda->campo('grado') == 3){ ?>selected="selected"<?php } ?>>3</option>
							<option value="4" <?php if($busqueda->campo('grado') == 4){ ?>selected="selected"<?php } ?>>4</option>
							<option value="5" <?php if($busqueda->campo('grado') == 5){ ?>selected="selected"<?php } ?>>5</option>
							<option value="6" <?php if($busqueda->campo('grado') == 6){ ?>selected="selected"<?php } ?>>6</option>
						</select>
						<label for="letra">Letra</label>
						<input type="text" name="letra" id="letra" value="<?php echo $busqueda->campo('letra') ?>" size="3" maxlength="1" />
						<label for="turno">Turno</label>
						<select name="turno" id="turno">
							<option></option>
							<option value="M" <?php if($busqueda->campo('turno') == 'M'){ ?>selected="selected"<?php } ?>>M</option>
							<option value="V" <?php if($busqueda->campo('turno') == 'V'){ ?>selected="selected"<?php } ?>>V</option>
							<option value="N" <?php if($busqueda->campo('turno') == 'N'){ ?>selected="selected"<?php } ?>>N</option>
						</select>
						<br/>
						<br/>
						<label for="oferta_id">Oferta</label>
						<select name="oferta_id" id="oferta_id">
							<option></option>
							<?php foreach($ofertas as $oferta){ ?>
							<option value="<?php echo $oferta->id; ?>" <?php if($busqueda->campo('oferta_id') == $oferta->id){ ?>selected="selected"<?php } ?>><?php echo $oferta->nombre; ?></option>
							<?php } ?>
						</select>
						<label for="situacion">Situaci&oacute;n</label>
						<select name="situacion" id="situacion">
							<option></option>
							<?php foreach($situaciones as $situacion){ ?>
							<option value="<?php echo $situacion->id ?>"
									<?php if($busqueda->campo('situacion') == $situacion->id){ ?>
										selected="selected"
									<?php } ?>>
									<?php echo $situacion->nombre ?>
							</option>
							<?php } ?>
						</select>
						<input type="submit" id="btn_submit" value="Filtrar" />
						<input type="reset" id="reset" value="Quitar filtros" />
					</fieldset>
				</form>
			</div>
		</div>
		<?php if($registros > 0){ ?>
				<table>
					<tr>
						<th>Foto</th>
						<th>Alumno</th>
						<th>Situaci&oacute;n</th>
						<?php if($acl['alumnos']['trayectoria'] || $acl['alumnos']['editar'] || $acl['alumnos']['eliminar'] || $acl['alumnos']['password'] || $acl['alumnos']['ubicar'] || $acl['alumnos']['amonestaciones'] ){ ?>
						<th>Opciones</th>
						<?php } ?>
					</tr>
					<?php
						$i = 0;
						foreach($alumnos as $alumno){
					?>
					<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
						<td>
							<a href="<?php echo $alumno->foto  ?>"
							   rel="lightbox[]"
							   title="<?php echo $alumno->ap . ' ' . $alumno->am . ' ' . $alumno->nombre ?>"
							   alt="<?php echo $alumno->ap . ' ' . $alumno->am . ' ' . $alumno->nombre ?>">
								<img src="<?php echo $alumno->foto ?>" class="thumb"/>
							</a>
						</td>
						<td>
							<?php if($acl['alumnos']['ver']){?>
							<a href="<?php echo $path . 'alumnos/ver/' . $alumno->id?>"
							   alt="Ver datos del alumno" title="Ver datos del alumno">
								<span class="uc">
									<?php echo $alumno->ap . ' '  . $alumno->am . ', '?>
								</span>
								<?php echo $alumno->nombre	?>
							</a>
							<?php } else{ ?>
								<span class="uc">
									<?php echo $alumno->ap . ' '  . $alumno->am . ', '?>
								</span>
								<?php echo $alumno->nombre	?>
							<?php } ?>
							<br />
							<span class="sub">
								<?php echo $alumno->codigo ?>
							</span>
							<span class="sub" style="color:#777777">
								<a href="<?php echo $path; ?>grupos/ver/<?php echo $alumno->grupos_id; ?>" title="Ir al grupo del alumno." style="color:#777777" ><?php echo $alumno->grado . '&deg;' . $alumno->letra . ' ' . $alumno->turno?></a>
							</span>
							<?php
								$articulos=new Alumnosconarticulo();
								$articulos=$articulos->articulosAlumno($alumno->id);
								if(count($articulos)>0){
									if( in_array($alumno->grupos_id, $asignados) || in_array('ALL', $asignados) ){
									?>


									<?php
									foreach($articulos as $art){
							  		?>
									<span class="articulo" title="<?php echo $art->clave.": ".$art->materia; ?>"><a class="sub" style="color:#CC0000" href="<?php echo $path . 'grupos/curso/' . $art->cursos_id?>">
									{<?php echo $art->clave; ?>}
									</a></span>
									<?php
									}
									?>

								<?php
							 	}
							  } ?>
							  <br/>
							  <?php
									$amtotal = $alumno->totalamonestaciones();
									if($amtotal > 0){ ?>
								<span class="fin">
								<?php
									echo $amtotal. ' amonestaci'.($amtotal==1 ? '&oacute;n' : 'ones');
								?>
								</span>
								<?php } ?>
						</td>
						<td>
							<span class="sub bold" style="color:#777777">
								<?php echo $alumno->situacion ?>
							</span>
						</td>
						<?php if($acl['alumnos']['trayectoria'] || $acl['alumnos']['editar'] || $acl['alumnos']['eliminar'] || $acl['alumnos']['password'] || $acl['alumnos']['ubicar'] || $acl['alumnos']['amonestaciones'] ){ ?>
							<td>
								<?php if( in_array($alumno->grupos_id, $asignados) || in_array('ALL', $asignados) ){?>
									<?php if($acl['alumnos']['cursos']){ ?>
									<a href="<?php echo $path . 'alumnos/cursos/' . $alumno->id?>"
										   alt="Cursos del alumno" title="Cursos del alumno">
										   <img src="<?php echo $path?>public/img/sp5/cursos.png" />
									</a>
									<?php } ?>
									<?php if($acl['alumnos']['kardex']){ ?>
									<a href="<?php echo $path . 'alumnos/kardex/' . $alumno->id?>"
										   alt="Kardex del alumno" title="Kardex del alumno">
										   <img src="<?php echo $path?>public/img/sp5/kardex.png" />
									</a>
									<?php } ?>

									<?php if($acl['alumnos']['editar']){ ?>
										<a href="<?php echo $path . 'alumnos/editar/' . $alumno->id?>"
										   alt="Editar datos del alumno" title="Editar datos del alumno">
										   <img src="<?php echo $path?>public/img/sp5/editar.png" />
										</a>
									<?php } ?>
									<?php if($acl['alumnos']['password']){ ?>
									<a href="<?php echo $path . 'alumnos/password/' . $alumno->id?>"
							   			alt="Cambiar el password del alumno" title="Cambiar password del alumno">
							   			<img src="<?php echo $path?>public/img/sp5/pass.png" />
									</a>
									<?php } ?>
									<?php if($acl['alumnos']['ubicar']){ ?>
									<a href="<?php echo $path . 'alumnos/ubicar/' . $alumno->id?>"
							   			alt="Ubicar al alumno" title="Ubicar al alumno">
							   			<img src="<?php echo $path?>public/img/sp5/ubicar.png" />
									</a>
									<?php } ?>
									<?php if($acl['alumnos']['trayectoria'] && $alumno->bachillerato()==2){ ?>
									<a href="<?php echo $path . 'alumnos/trayectoria/' . $alumno->id?>"
							   			alt="Ligar trayectoria especializante al alumno" title="Ligar trayectoria especializante al alumno">
							   			<img src="<?php echo $path?>public/img/sp5/trayectoria.png" />
									</a>
									<?php } ?>
									<?php if($acl['alumnos']['eliminar']){ ?>
										<a href="<?php echo $path . 'alumnos/eliminar/' . $alumno->id?>"
										   alt="Eliminar toda la informacion del alumno" title="Eliminar toda la informacion del alumno">
										   <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
										</a>
									<?php } ?>
								<?php  } ?>
				  					<?php if($acl['alumnos']['amonestaciones']){?>
										<a href="<?php echo $path . 'alumnos/amonestaciones/' . $alumno->id?>"
										   alt="Amonestaciones del alumno" title="Amonestaciones del alumno">
										   <img src="<?php echo $path?>public/img/sp5/articulo.png" />
										</a>
									<?php } ?>
							</td>
						<?php } ?>
					</tr>
					<?php
						$i++;
					}
					?>
				</table>
		<?php } else { ?>
				<p class="info"><br />No hay registros que mostrar...</p>
		<?php } ?>
		<div id="pages">
			<?php foreach($paginador->botones() as $boton){ ?>
				 <a  href="<?php echo $path . $boton->url() ?>"
					title="Ir a la p&aacute;gina <?php echo $boton->titulo() ?>"
					class="<?php echo $boton->estilo() ?>">
					<?php echo $boton->etiqueta() ?>
				</a>
			<?php }?>
		</div>
	</div>
</div>