<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Recuperar informacion</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>alumnos">Volver a alumnos
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
<?php if($option=="captura"){ ?>
<form action="<?php echo $path ?>alumnos/recuperar" id="frm_editar" method="post" enctype="multipart/form-data">
<fieldset>
    Realizar recuperacion.
    <div id="botones">
    <input type="submit" name="boton" id="boton" value="Aceptar" />
    </div>
</fieldset>
</form>
<?php }elseif($option="exito"){ ?>
<p class="info">Se realizo con exito.</p>
<?php echo count($recuperados); ?>
<table>
<tr><th>#</th><th>id</th><th>nombre</th></tr>
<?php $i=1; foreach($recuperados as $alumno){ ?>
<tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
<td><?php echo $i; ?></td>
<td><?php echo $alumno->id; ?></td>
<td><?php echo $alumno->nombre(); ?><br/><span class="sub"><?php echo $alumno->codigo; ?></span></td></tr>
<?php
        $i++;
    } ?>
</table>
<?php }else{ ?>
<p class="error"><?php echo $error; ?></p>
<?php } ?>
</div>
</div>