<?php $path = KUMBIA_PATH; ?>
<?php if($option == 'ajax'){?>
        Profesor
        <br />
        <select name="usuarios[]">
        <option></option>
        <?php foreach($profesores as $usr){ ?>
            <option value="<?php echo $usr->id ?>"
                    alt="<?php echo $usr->ap . ' ' . $usr->am . ', ' .$usr->nombre ?>"
                    title="<?php echo $usr->ap . ' ' . $usr->am . ', ' .$usr->nombre ?>" >
                <?php echo $usr->ap . ' ' . $usr->am . ', ' .$usr->nombre ?>
            </option>
        <?php }?>
        </select>
        <br />
<?php }else{ ?>
        <div id="primary">
            <div class="content">
                <h1>Asignar tutor.</h1>
                <div id="options-bar">
                    <div id="options">
                        <a href="<?php echo $path ?>tutoresgrupo">Volver
                        <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                        </a>
                    </div>
                </div>
                <?php switch($option) {
                        case 'captura': ?>
                            <form action="<?php echo $path ?>tutoresgrupo/asignar" id="frm_asignar" method="post">
                                <fieldset>
                                    <legend>Ciclo</legend>
                                    <?php echo $ciclo->numero ?>
                                    <br/>
                                </fieldset>

                                <fieldset>
                                    <legend>Grupo</legend>
                                    <input type="hidden" name="grupos_id" id="grupos_id" value="<?php echo $grupo->id ?>" />
                                    <?php echo $grupo->grado . '&deg;' . $grupo->letra . ' ' . $grupo->verTurno()?>
                                    <br />
                                </fieldset>
                                <div class="separador"></div>
                                <fieldset>
                                    <legend>Profesores</legend>
                                    <div id="usuarios">
                                        <?php
                                                foreach($grupo->tutores() as $encargado){
                                        ?>
                                                Profesor
                                                <br />
                                                <select name="usuarios[]">
                                                <option></option>
                                                <?php foreach($profesores as $usr){ ?>
                                                    <option value="<?php echo $usr->id ?>"
                                                            alt="<?php echo $usr->ap . ' ' . $usr->am . ', ' .$usr->nombre ?>"
                                                            title="<?php echo $usr->ap . ' ' . $usr->am . ', ' .$usr->nombre ?>"
                                                            <?php if($usr->id == $encargado->profesores_id){?> selected="selected"<?php } ?>
                                                    >
                                                        <?php echo $usr->ap . ' ' . $usr->am . ', ' .$usr->nombre ?>
                                                    </option>
                                                <?php }?>
                                                </select>
                                                <br />
                                        <?php
                                                $n++;
                                             }
                                         ?>
                                    </div>
                                    <img id="spinner" src="<?php echo $path ?>/public/img/sp5/spinner.gif" style="display:none"/>
                                    <a href="#" id="agregar"><img src="<?php echo $path . 'img/sp5/mas.png' ?>" /></a>
                                    <br />
                                </fieldset>
                                <div></div>
                                <div id="botones">

                                    <input type="button" id="aceptar" value="Guardar">
                                    <input type="button" id="cancelar" value="Cancelar">

                                </div>
                            </form>
                        <?php  break; ?>
                    <?php case 'exito': ?>
                        <p class="info"><br />Los tutores del grupo <?php echo $grupo->grado . '&deg;' . $grupo->letra . ' ' . $grupo->verTurno()?>(<?php echo $ciclo->numero; ?>)<br/> se agregaron correctamente</p>
                    <?php  break; ?>
                    <?php case 'error':
                          default:
                    ?>
                        <p class="error"><br />Ha ocurrido un error.
                            <?php echo $error ?>
                        </p>
                    <?php  break; ?>
                <?php } ?>
            </div>
        </div>
<?php } ?>