<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar calificaciones</h1>
		<h2><?php echo $materia->nombre ?></h2>
		<h2>
			<?php echo 'Prof. ' . $curso->verProfesor() ?></h2>
		<h2>
			<?php echo $grupo->grado .'&deg;' .  $grupo->letra .  ' ' . $grupo->verTurno() . ', ' . $ciclo->numero?>
		</h2>
		<h2><?php echo  $grupo->verOferta(); ?></h2>
		<?php switch($option) {
				case 'captura': ?>

				<div id="options-bar">
					<div id="options">
						<a href="<?php echo $path . 'calificaciones/ver/' . $curso->id ?>">Volver a calificaciones
						<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
					</div>
				</div>
				<div id="calificaciones" class="contenedor">
					<form name="frm_editar" id="frm_editar" method="post">
					<input type="hidden" name="cursos_id" id="cursos_id" value="<?php echo $curso->id ?>" />
					<div>
					<table id="main">
						<?php $n = 1; ?>
						<?php $i = 1; ?>
						<?php foreach($alumnos as $alumno){?>
							<?php if(($n - 1) % 10 == 0){ ?>
							<tr>
								<th rowspan="2">#</th>
								<th rowspan="2">Alumno</th>
								<?php if($nParciales > 0){ ?>
									<th colspan="<?php echo $nParciales ?>">Parciales</th>
								<?php } ?>
								<?php if($nCalificaciones > 0){ ?>
									<th colspan="<?php echo $nCalificaciones ?>">Finales</th>
								<?php } ?>
							</tr>
							<tr>
								<?php foreach($parciales as $nParcial => $parcial){?>
									<th style="background-color: #EEEEFE;"><?php echo $nParcial ?></th>
								<?php } ?>
								<?php foreach($calificaciones as $idCal => $calificacion){?>
									<th style="background-color: #EEEEFE;">
										<?php echo $idCal ?>
									</th>
								<?php } ?>
							</tr>
							<?php } ?>
							<tr>
								<td  class="<?php echo ($n%2 != 0 ? '' : 'odd') ?>">
									<?php echo $n ?>
								</td>
								<td  class="<?php echo ($n%2 != 0 ? '' : 'odd') ?>">
									<?php echo $alumno->nombre()  ?>
									<br />
									<span class="sub"><?php echo $alumno->codigo ?><span>
									<span class="sub" style="color: #777">
										<?php echo $alumno->grado . '&deg;' . $alumno->letra . ' ' . $alumno->turno?>
									</span>
								</td>
								<?php foreach($parciales as $nParcial => $parcial){?>
									<?php
										$valor = $vParcial[$alumno->id][$nParcial];
										$id = $vParcial[$alumno->id]['id_' .$nParcial];
										if($materia->duracion==7){
										$clavePrc = 'CPC-' . str_pad($nParcial, 3, "0", STR_PAD_LEFT);
										}else{
										$clavePrc = 'PRC-' . str_pad($nParcial, 3, "0", STR_PAD_LEFT);
										}
										$modo = 'EDI';
										if($id == ''){
											$modo = 'AGR';
											$id = $alumno->id;
										}
									?>
									<td id="td_<?php echo $i ?>"
									    class="<?php echo ($n%2 != 0 ? '' : 'odd') ?>  <?php echo ($valor >= 60 ? 'TRUE' : 'FALSE')?> switch">
										<a id="a_<?php echo $i ?>" class="switch" alt="Presione para editar" title="Presione para editar">
									   		<?php echo $valor?>
									   	</a>
										<input type="text"
											   name="parciales[<?php echo $modo ?>][<?php echo $clavePrc ?>][<?php echo $id ?>]"
											   class="calificacion"
											   size="3"
											   maxlength="3"
											   id="cal_<?php echo $i ?>"
											   value="<?php echo $valor ?>"
											   disabled="disabled"
											   style="display:none" />
									</td>
									<?php $i++ ?>
								<?php } ?>
								<?php $oportunidad = $curso->oportunidadClaveAlumno($alumno->id, 'AST-ORD'); ?>
								<?php $ast = $curso->oportunidadClaveAlumno($alumno->id, 'AST'); ?>
								<?php foreach($calificaciones as $idCal => $calificacion){ ?>
							 			<?php
							 				$valor = $vCalificacion[$alumno->id][$idCal]['valor'];
							 				$id = $vCalificacion[$alumno->id][$idCal]['id'];
							 				$modo = 'EDI';

							 				if($valor == 'SD'){
							 					$valor = 50;
							 				}

							 				if($id == ''){
							 					$modo = 'AGR';
							 					$id = $alumno->id;
							 				}
							 			?>

  									 	<?php if( $idCal == $oportunidad  || ($idCal == 'ORD' &&  $ast == 'ORD' && $oportunidad == 'EXT')){ ?>
												<?php if($materia->tipo != 'TLR' && $materia->tipo != 'PRO'){ ?>
													<td id="td_<?php echo $i ?>"
				  									 	class="<?php echo ($n%2 != 0 ? '' : 'odd') ?> <?php echo ($valor >= 60 ? 'TRUE' : 'FALSE')?> switch">
														<a id="a_<?php echo $i ?>" class="switch" alt="Presione para editar" title="Presione para editar">
													   		<?php echo $valor?>
													   	</a>
													   	<span id="sp_<?php echo $i ?>" style="display:none">-</span>
														<input type="text"
															   name="calificaciones[<?php echo $modo?>][<?php echo $calificacion?>][<?php echo $id ?>]"
															   class="<?php echo ($ordExtSimultaneos && $idCal == 'ORD' ? 'ordinario' : 'calificacion')?>"
															   size="3"
															   maxlength="3"
															   id="cal_<?php echo $i ?>"
															   value="<?php echo $valor ?>"
															   <?php if($valor != ''){ ?>
															   disabled="disabled"
															   style="display:none"
															   <?php } ?>
															   />
												   </td>
											   <? } else{ ?>
												   <td id="td_<?php echo $i ?>"
				  									 	class="<?php echo ($n%2 != 0 ? '' : 'odd') ?> <?php echo ($valor == 'A'  || $valor>=60 ? 'TRUE' : 'FALSE')?> switch">
													   	<a id="a_<?php echo $i ?>" class="switch" alt="Presione para editar" title="Presione para editar">
													   		<?php echo ($valor == 'A' || $valor>=60 ? 'Acreditado' : 'No acreditado') ?>
													   	</a>
													   	<select name="calificaciones[<?php echo $modo?>][<?php echo $calificacion?>][<?php echo $id ?>]"
													   	        class="calificacion"
													   	        id="cal_<?php echo $i ?>"
													   	        disabled="disabled"
													   	        style="display:none" />
													   		<option value="A" <?php if($valor == 'A'  || $valor>=60){ ?> selected="selected" <? } ?>>Acreditado</option>
													   		<option value="NA"  <?php if($valor == 'NA' || $valor<=59){ ?> selected="selected" <? } ?>>No acreditado</option>
													   </select>
												   </td>
											   <?php } ?>
									   <?php }else if($oportunidad == 'ORD'){ ?>
									   			<td id="td_<?php echo $i ?>"
				  								 	class="<?php echo ($n%2 != 0 ? '' : 'odd') ?>">
										   			<span id="sp_<?php echo $i ?>">-</span>
													<input type="text"
														   name="calificaciones[<?php echo $modo?>][<?php echo $calificacion?>][<?php echo $id ?>]"
														   class="<?php echo ($ordExtSimultaneos && $idCal == 'ORD' ? 'ordinario' : 'calificacion')?>"
														   size="3"
														   maxlength="3"
														   id="cal_<?php echo $i ?>"
														   value="<?php echo $valor ?>"
														   disabled="disabled"
														   style="display:none" />
									   			</td>
									   <?php }else{ ?>
											   	<td id="td_<?php echo $i ?>"
				  									class="<?php echo ($n%2 != 0 ? '' : 'odd') ?> FALSE">
												   	<span class="false">Sin derecho</span>
											   		<input type="hidden"
											   		       name="calificaciones[<?php echo $modo?>][<?php echo $calificacion ?>][<?php echo $id ?>]"
											   		       value="SD" />
											   	</td>
									   <?php } ?>
									<?php $i++ ?>
								<?php } ?>
							</tr>
						<?php $n++; ?>
						<?php } ?>
					</table>
					</div>
					<div id="botones">
						<input type="submit" value="Editar" />
						<input type="button" id="cancelar" value="Cancelar" />

					</div>
					</form>
				</div>
			<?php  break; ?>
			<?php case 'exito': ?>
				<div id="options-bar">
					<div id="options">
						<a href="<?php echo $path . 'calificaciones/ver/' . $curso->id ?>">Volver a calificaciones
						<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
					</div>
				</div>
				<p class="info">
					<br />
					<?php echo $exito ?>
				</p>
			<?php  break; ?>
			<?php case 'alert': ?>
				<div id="options-bar">
					<div id="options">
						<a href="<?php echo $path . 'calificaciones/ver/' . $curso->id ?>">Volver a calificaciones
						<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
					</div>
				</div>
				<p class="info">
					<br />
					<?php echo $alert ?>
				</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<div id="options-bar">
					<div id="options">
						<a href="<?php echo $path . 'grupos' ?>">Volver a grupos
						<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
					</div>
				</div>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>