<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Eliminar grupo del ciclo <?php echo $ciclo->numero?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>grupos">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>grupos/eliminar/" id="frm_eliminar" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $grupo->id ?>" />
					<p class="error">
						Se dispone a eliminar toda la informaci&oacute;n del grupo 
						<?php echo $grupo->grado . '&deg;' .$grupo->letra . ' ' . $grupo->verTurno() ?>
						<br />
						<strong>&iquest;Desea continuar?</strong>
					</p>
					<div id="botones">
						<input type="button" id="aceptar" value="Aceptar">
						<input type="button" id="cancelar" value="Cancelar">					
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El grupo se elimin&oacute; correctamente.</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">Ha ocurrido un error al intentar eliminar el grupo.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>