<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Horario</h1>
		<?php switch($option) {
				case 'vista': ?>
					<h2>
						<?php echo $grupo->grado . '&deg;' . $grupo->letra . ' ' . $grupo->verTurno(); ?>
					</h2>
					<h2><?php echo  $grupo->verOferta(); ?></h2>
					<h2 class="info">
						<?php echo $nCursos ?>
						Curso<?php echo ($nCursos == 1 ? '' : 's') ?>
						registrado<?php echo ($nCursos == 1 ? '' : 's') ?>
					</h2>
					<div id="options-bar">
						<div id="options">
							<a href="<?php echo $path . 'grupos/ver/' . $grupo->id ?>"
							   alt="Volver al resumen"
							   title="Volver al resumen">Volver a grupo
							<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
						</div>
					</div>
			<?php
			//$inicio=7;
			//$fin=13;
			?>
			<table>
			<tr>
			<th>Hora</th>
			<?php
			foreach($dias as $d){
			?>
			<th><?php echo $d->nombre; ?></th>
			<?php
			}
			?>

			</tr>

			<?php
			//$inicio=7;
			//$fin=13;

			for($ini=$inicio;$ini<$fin;$ini++){
			?>
			<tr>
			<th><?php echo '<span class="sub">'.$ini.":00-".($ini+1).":00</span>"; ?></th>
			<?php
			foreach($dias as $d){
				$b=false;
				$crs="";
				foreach($cursos as $c){
				$horarios=$c['h'];
				foreach($horarios as $h){
					$i=substr($h->inicio,0,2);
					$f=substr($h->fin,0,2);
					if($h->dias_id==$d->id
					&&
					(
					($i<=$ini)
					&&
					($f>=($ini+1))
					)
					){
					$curso=$c['c'];
					$grupo=$curso->grupo();
					$b=true;
			?>
			<?php
					$materia=$curso->materia();
					$crs.= '<div >' .
							'<span style="color: rgb(119, 119, 119);" class="sub">'.Utils::convierteFecha($curso->inicio).'</span>' .
							'<br/>';

							if($acl['grupos']['curso']){
							$crs.='<a href="'.$path.'grupos/curso/'.$curso->id.'">'.$materia->nombre.'</a><br/><span class="sub">'.$h->aulaNombre()."</span>" ;
							}else{
							$crs.='<span class="sub">'.$materia->nombre."<br/>".$h->aulaNombre()."</span>" ;
							}

					$crs.="</div>" .
							"<br/>";
							 ?>
			<?php
					//break 2;
					}

				}
				}
				if(!$b){
				?>
				<td style="text-align:center"><span class="main"> - </span></td>
				<?php
				}else{
					?>
					<td class="odd" style="text-align:center"><?php echo $crs; ?></td>
				<?php
				}
			}
			?>
			</tr>
			<?php
			}

			?>
			</table>


				<?php break; ?>
				<?php case 'alert': ?>
					<div id="options-bar">
						<div id="options">
							<a href="<?php echo $path . 'grupos/ver/' . $grupo->id ?>"
							   alt="Volver al resumen"
							   title="Volver al resumen">Volver a grupo
							<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
						</div>
					</div>
					<p class="info">
						<br />
						<?php echo $alert ?>
					</p>
				<?php  break; ?>
				<?php case 'error':
					  default:
				?>
					<div id="options-bar">
						<div id="options">
							<a href="<?php echo $path . 'grupos' ?>">Volver a grupos
							<img src="<?php echo $path?>public/img/sp5/volver.png"/></a>
						</div>
					</div>
					<p class="error">
						<br />
						<?php echo $error ?>
					</p>
				<?php  break; ?>
		<?php } ?>
	</div>
</div>