<h1>Bienvenido a control escolar.</h1>
<p>Por favor seleccione el tipo de usuario. Introduzca el codigo del alumno e introduzca su contraseña.</p>

   <div id="info"></div>
  <div style="float: left;margin-left: 20%;">

  <?php echo form_tag("escolar/abrir", "id: frm_login"); ?>
    <fieldset>
    <p class="formulario" >Alumno <input title="Seleccione el tipo de usuario." id="alumno" type="radio" name="tipo" value="A"  checked="checked" /> Tutor <input  title="Seleccione el tipo de usuario." id="tutor" type="radio" name="tipo" value="T"/></p>
    <p class="formulario" >Codigo <input title="Introduzca el codigo de alumno." name="codigo" id="codigo" type="text" size="15" maxlength="25"  /></p>
    <p class="formulario" >Contrase&ntilde;a <input title="Introduzca su contraseña." name="pass" type="password" id="pass" size="15" maxlength="25" /></p>
    <p class="formulario" title="" style="text-align:right;width: 70%;"><input title="Presione para entrar." id="btn" type="button"  name="Entrar" value="Entrar"/></p>
    </fieldset>
      <input type="hidden" name="path" id="path" value="<?php echo KUMBIA_PATH; ?>"/>

   <?php echo end_form_tag() ?>
   </div>
   
        <div id="informacion_usuarios">
                <p>Puede ingresar con las siguientes cuentas de alumno y tutor:</p>
                <p>
                    <ul>
                        <li>367991687</li>
                        <li>465420622</li>
                        <li>481090522</li>
                        <li>319110918</li>
                    </ul>
                    
                <p>La contraseña para todas las cuentas es <span style="font-weight: bold">hekademos</span>.</p>
                </p>
        </div>
   <br/>
