<?php if($cambia){?>
    <div>
    <?php  echo $msj; ?>
    </div>
<?php }else{ ?>
<h1>Cambiar Password</h1>
<form action="<?php echo KUMBIA_PATH . 'escolar/password/cambia'?>" method="post" id="form">
<fieldset>
<legend style="font-weight:bold">Nuevos datos de acceso</legend>
<p style="text-align:left;">Nuevo password <input title="Por favor escriba su nuevo password." id="p1" name="p1" type="password" maxlength="15" size="15"/></p>
<p style="text-align:left;">Confirme password <input title="Es necesario confirmar su nuevo password para verificar que haya sido escrito en forma correcta." id="p2" name="p2" type="password" maxlength="15" size="15"/></p>
<p style="text-align:left;">Password actual <input title="El password actual es necesario para verificar su identidad." id="p3" name="p3" type="password" maxlength="15" size="15"/>
</fieldset>
<div style="height:10px;"></div>
<p style="text-align:right;width:220px;margin:0 auto;text-align:right;" ><input title="Presione para realizar el cambio." id="cancelar" type="button" value="cancelar"/><input title="Presione para realizar el cambio." id="btn" type="button" value="aceptar"/></p>
</form>
<?php } ?>