<h1>Registro</h1>
<div id="options-bar">
    <div id="options">
    <a title="Volver a inicio." class="submenu" href="<?php echo KUMBIA_PATH?>escolar/agenda">Volver agenda <img src="<?php  echo KUMBIA_PATH?>img/sp5/volver.png" alt="Volver a inicio"/></a>
    </div>
</div>
<br/>
<?php switch($option) {
    case "captura":

        if($escolar->ofertantrayectorias($periodo_id)){
        if(is_array($trayectoria) && count($trayectoria)>0){ ?>
        <div>
        <h2>Trayectoria especializante</h2>
        <br/>
          <p class="infoBox"><br/><?php echo $trayNombre; ?><br/></p>

        </div>

        <?php
        }else{
        ?>
        <br/>
        <p class="infoBox">
        <br/>
        Aun no realiza su registro.
        </p>
        <?php
        }
        }


        if($escolar->ofertancursos($periodo_id)){
        if(is_array($inscritos) && count($inscritos)>0){ ?>
        <div>
        <h2>Cursos</h2>
        <table class="widget" id="grado_<?php echo $tipos[0]['grado'];?>_tipo_<?php echo $t;  ?>">
        <tr><th>Grupo</th><th>Curso</th></tr>
        <?php
            $i=0;
            foreach($inscritos as $ins){ ?>
        <tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
            <td>
            <span class="sub"><?php echo $ins['grado'].$ins['letra']; ?></span>
        <br/>
        <span class="sub"><?php echo $escolar->regresaTurno($ins['turno']); ?></span>
        <br/>
        <span class="sub"><?php echo $ins['grupo_oferta']; ?></span>
        </td>
        <td>
        <span class="sub"><?php echo $ins['nombre']; ?></span>
        <br/>
        <span class="sub" style="color: rgb(119, 119, 119);">
        <?php echo $escolar->materiaTipo($ins['tipo']);?>
        </span>
        </td>

        </tr>
        <?php
            $i++;
         } ?>
        </table>

        </div>

        <?php
        }else{
        ?>
        <br/>
        <p class="infoBox">
        <br/>
        Aun no realiza su registro.
        </p>
        <?php
        }
        }
        break;

        default:
        case "error":
        ?>
        <p class="errorBox"><br/>Ha ocurrido un error<br/><?php echo $error; ?></p>
        <?php
        break;


    }
        ?>


