<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Ayuda</h1>
        <p class="msj">
            <br />
            Seleccione el manual que desea consultar.
        </p>
        <ul class="opciones">
        <?php foreach($grupos as $grupo){ ?>
            <li>
                <a href="<?php echo $path . 'public/man/' . $grupo . '.pdf' ?>">
                    <?php echo ucfirst($grupo) ?>
                </a>
            </li>
        <? } ?>
        </ul>
    </div>
</div>