<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Agregar ciclo</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>accesos">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'exito': ?>
                <p class="info"><br />
                    <?php echo $exito ?>
                </p>
            <?php  break; ?>
            <?php case "confirmar": ?>
            <form action="<?php echo $path ?>accesos/generar/" id="frm_agregar" method="post">
                    <p class="error" style="text-align:left;padding-left:100px">

                        Se dispone a crear accesos para <?php echo $tipo; ?>  <br/>
                        <input type="hidden" name="id" value="<?php echo $tipo; ?>" />

                        <strong>&iquest;Desea continuar?</strong>
                    </p>
                      <div id="botones">
                        <input type="submit" id="aceptar_c" value="Aceptar">
                        <input type="button" id="cancelar_c" value="Cancelar">

                    </div>
                </form>

            <?php break;  ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error"><br />
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>