<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Plantilla</h1>

        <ul class="opciones">
            <li>
                <a href="<?php echo $path ?>plantilla/materias">Carga horaria por materia/unidad</a>
            </li>
            <li>
                <a href="<?php echo $path ?>plantilla/profesores">Prerregistro de cursos por profesor</a>
            </li>
            <li>
                <a href="<?php echo $path ?>plantilla/profesoreshoras">Reporte horas asignadas</a>
            </li>
        </ul>
    </div>
</div>