<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Profesores</h1>
        <h2 class="sub">Prerregistro de cursos</h2>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>plantilla">Volver
                    <img src="<?php echo $path?>public/img/sp5/volver.png" alt="volver"/>
                </a>
            </div>
        </div>
        <?php switch($option) { 
            case 'exito': ?>
                <p class="info">
                    <br />
                    <?php echo $exito ?>
                </p>
        <?php break;?>
        
        <?php case 'error': ?>
                <p class="error">
                    <br />
                    <?php echo $error ?>
                </p>
        <?php break;?>
        
    <?php }?>
    </div>
</div>