<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Cancelar amonestación</h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>amonestaciones">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>amonestaciones/cancelar/" id="frm_eliminar" method="post">
                    <input type="hidden" name="id" id="id" value="<?php echo $amonestacion->id ?>" />
                    <input type="hidden" name="KUMBIA_PATH" id="KUMBIA_PATH" value="<?php echo $path ?>" />
                    <p class="error">
                        <?php if(count($amonestados) > 1){ ?>
                        Se dispone a <strong>cancelar</strong> la amonestación grupal asignada a 
                        <?php $grupo = $amonestados[0]->grupo() ?>
                        <?php echo $grupo->grado.'°'.$grupo->letra.' '.$grupo->turno.' '.$grupo->verOferta()?>
                    <?php }else{ ?>
                        Se dispone a <strong>aprobar</strong> la amonestación del alumno
                            <?php foreach($amonestados as $amonestado){ 
                            $alumno = $amonestado->alumno();                        
                        ?>
                        <?php echo $alumno->codigo . ', ' .$alumno->nombre(); ?><br/>
                        <?php } ?>
                    
                        con fecha del
                        <?php echo $amonestacion->fecha; ?>
                    <?php } ?>
                        <br />
                        <strong>&iquest;Desea continuar?</strong>
                    </p>
                    <div id="botones">
                        <input type="submit" id="aceptar" value="Aceptar">
                        <input type="button" id="cancelar" value="Cancelar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />La amonestación se cancel&oacute; correctamente.</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error">Ha ocurrido un error al intentar cancelar la amonestación.<br />
                <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>