<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Editar personal <?php echo $personal->codigo?></h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>personal">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>personal/editar" id="frm_editar" method="post" enctype="multipart/form-data">
                    <fieldset>
                    <legend>Tipo</legend>
                    <select name="tipopersonal_id" id="tipopersonal_id">
                        <option value=""></option>
                        <?php foreach($tipos as $tipo){?>
                        <option value="<?php echo $tipo->id; ?>" <?php if($personal->tipopersonal_id==$tipo->id){ ?>selected="selected"    <?php } ?>><?php echo $tipo->nombre; ?></option>
                          <?php } ?>
                      </select>

                    </fieldset>
                    <fieldset>
                        <legend>Personal</legend>
                        <input type="hidden" name="id" id="id" value="<?php echo $personal->id ?>" />
                        <label for="nombre">Nombre</label><br />
                        <input type="text" name="nombre" id="nombre" size="30" maxlength="30" value="<?php echo $personal->nombre ?>" /><br />
                        <label for="ap">Apellido paterno</label><br />
                        <input type="text" name="ap" id="ap" size="20" maxlength="20" value="<?php echo $personal->ap ?>" /><br />
                        <label for="am">Apellido materno</label><br />
                        <input type="text" name="am" id="am" size="20" maxlength="20" value="<?php echo $personal->am ?>" /><br />
                        <label for="rfc">RFC</label><br />
                        <input type="text" name="rfc" id="rfc" size="20" maxlength="20" value="<?php echo $personal->rfc ?>" /><br />
                        <label for="curp">CURP</label><br />
                        <input type="text" name="curp" id="curp" size="20" maxlength="20" value="<?php echo $personal->curp ?>" />
                        <label><input type="radio" name="sexo" value="M" <?php if($personal->sexo == 'M'){ ?>checked="checked"<?php }?>/> Mujer </label>
                        <label><input type="radio" name="sexo" value="H" <?php if($personal->sexo == 'H'){ ?>checked="checked"<?php }?>/> Hombre </label><br />
                        <label for="fnacimiento">Fecha de nacimiento</label><br />
                        <input type="text" name="fnacimiento" id="fnacimiento" size="10" maxlength="10" value="<?php echo $personal->fnacimiento ?>" />
                        <a href="#" id="cal"><img src="<?php echo $path ?>/public/img/sp5/calendario.png" /></a><br />
                        <label for="foto">Foto</label><br />
                        <?php if($personal->foto != ''){ ?>
                        <input type="hidden" id="cambiar" name="cambiarImagen" value="false" />
                        <div id="imagen" />
                            <br />
                            <img class="ficha"
                                 src="<?php echo KUMBIA_PATH . 'public/img/personal/' . $personal->foto . '?d=' .time()?>"/>
                            <br />
                            <input type="button" id="iCambiar" value="Cambiar imagen" />
                        </div>
                        <div id="examinar" style="display:none">
                            <input type="file" id="foto" name="foto" />
                            <input type="button" id="iCancelar" value="Cancelar" />
                        </div>
                        <?php }else{ ?>
                                <input type="hidden" id="cambiar" name="cambiarImagen" value="true" />
                                <input type="file" id="foto" name="foto" />
                        <?php } ?>
                    </fieldset>
                    <div></div>
                    <fieldset>
                        <legend>Contacto</legend>
                        <label for="domicilio">Domicilio</label><br />
                        <input type="text" name="domicilio" id="domicilio" size="30" maxlength="60" value="<?php echo $personal->domicilio ?>" /><br />
                        <label for="tel">Tel&eacute;fono</label><br />
                        <input type="text" name="tel" id="tel" size="20" maxlength="20" value="<?php echo $personal->tel ?>" /><br />
                        <label for="tel">Tel&eacute;fono m&oacute;vil</label><br />
                        <input type="text" name="cel" id="cel" size="20" maxlength="20" value="<?php echo $personal->cel ?>" /><br />
                        <label for="mail">Correo electr&oacute;nico</label><br />
                        <input type="text" name="mail" id="mail" size="30" maxlength="80" value="<?php echo $personal->mail ?>" /><br />
                    </fieldset>
                    <div id="botones">
                        <input type="button" id="aceptar" value="Editar">
                        <input type="button" id="cancelar" value="Cancelar">

                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />El personal se edit&oacute; correctamente</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error"><br />Ha ocurrido un error al intentar editar el personal
                    <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>