<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Eliminar personal <?php echo $personal->codigo?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>personal">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) {
				case 'captura': ?>
				<form action="<?php echo $path ?>personal/eliminar/" id="frm_eliminar" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $personal->id ?>" />
					<p class="error">
						Se dispone a eliminar toda la informaci&oacute;n del personal
						<?php echo $personal->codigo?>,
						<?php echo $personal->nombre .' ' . $personal->ap . ' ' . $personal->am?>
						<br />
						<strong>&iquest;Desea continuar?</strong>
					</p>
					<div id="botones">
						<input type="button" id="aceptar" value="Aceptar">
						<input type="button" id="cancelar" value="Cancelar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El personal se elimin&oacute; correctamente.</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error">Ha ocurrido un error al intentar eliminar el personal.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>