<div id="primary">
    <div class="content">
        <h1>
            <?php echo $registros;?>
            Personal
            <?php if($busqueda->condicion() != '') {?><div class="filter-lab">Contenido filtrado</div><?php }?>
        </h1>
        <div id="options-bar">
            <div id="options">
            <?php if($acl['buscar']){ ?>
                <a href="" id="aSearch" title="Buscar" alt="Buscar">
                    Buscar
                    <img src="<?php echo $path?>public/img/sp5/buscar.png"/>
                </a>
                <?php } ?>
                <?php if($acl['exportar']){ ?>
                  /
                  <a href="<?php echo $path . 'personal/exportar/' ?>" title="Exportar personal" alt="Exportar personal">
                    Exportar
                    <img src="<?php echo $path?>public/img/sp5/excel.png"/>
                </a>

                 <?php } ?>
                 <?php if($acl['agregar']){ ?>
                /
                <a href="<?php echo $path ?>personal/agregar" title="Agregar personal" alt="Agregar personal">
                    Agregar personal
                    <img src="<?php echo $path?>public/img/sp5/nuevo.png"/>
                </a>
                <?php } ?>
                  /
                  <a href="<?php echo $path . 'tipopersonal' ?>" title="Tipo personal" alt="Tipo personal">
                    Tipo personal
                    <img src="<?php echo $path?>public/img/sp5/cursos.png"/>
                </a>

            </div>
            <?php if($acl['buscar']){ ?>
            <div id="search" <?php if($busqueda->condicion() == ''){?> style="display:none" <?php } ?>>
                <form action="<?php echo $path ?>personal" method="post" id="frm_search">
                    <fieldset>
                        <label for="codigo">C&oacute;digo</label>
                        <input type="text" name="codigo" id="codigo" value="<?php echo $busqueda->campo('codigo') ?>" size="15" maxlength="12" />
                        <label for="nombre">Nombre</label>
                        <input type="text" name="nombre" id="nombre" value="<?php echo $busqueda->campo('nombre') ?>" size="20" maxlength="70" />
                        <label for="sexo">Sexo</label>
                        <select name="sexo" id="sexo">
                            <option></option>
                            <option value="H" <?php if($busqueda->campo('sexo') == 'H'){ ?>selected="selected"<?php } ?>>H</option>
                            <option value="M" <?php if($busqueda->campo('sexo') == 'M'){ ?>selected="selected"<?php } ?>>M</option>
                        </select>
                        <label for="tipopersonal_id">Tipo</label>
                        <select name="tipopersonal_id" id="tipopersonal_id">
                        <option value=""></option>
                        <?php foreach($tipos as $tipo){?>
                        <option value="<?php echo $tipo->id; ?>" <?php if($busqueda->campo('tipopersonal_id')==$tipo->id){ ?>selected="selected"<?php } ?>><?php echo $tipo->nombre; ?></option>
                          <?php } ?>
                          </select>
                        <input type="submit" id="btn_submit" value="Filtrar" />
                        <input type="reset" id="reset" value="Quitar filtros" />
                    </fieldset>
                </form>
            </div>
            <?php } ?>
        </div>
        <?php if($registros > 0){ ?>
                <table>
                    <tr>
                        <th>Foto</th>
                        <th>Nombre</th>
                        <?php if($acl['editar'] || $acl['eliminar'] || $acl['password']){ ?>
                        <th>Opciones</th>
                        <?php } ?>
                    </tr>
                    <?php
                        $i = 0;
                        foreach($elementos as $elemento){
                    ?>
                    <tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
                        <td>
                            <a href="<?php echo $elemento->foto  ?>"
                               rel="lightbox[]"
                               title="<?php echo $elemento->ap . ' ' . $elemento->am . ' ' . $elemento->nombre ?>"
                               alt="<?php echo $elemento->ap . ' ' . $elemento->am . ' ' . $elemento->nombre ?>">
                                <img src="<?php echo $elemento->foto ?>" class="thumb"/>
                            </a>
                        </td>
                        <td>

                            <a href="<?php echo $path . 'personal/ver/' . $elemento->id?>"
                                   alt="Ver datos del personal" title="Ver datos del personal">
                                <span class="uc">
                                    <?php echo $elemento->ap . ' '  . $elemento->am . ', '?>
                                </span>
                                <?php echo $elemento->nombre    ?>
                            <br/>
                            <span class="sub">
                                    <?php echo $elemento->tipo(); ;?>

                            </span>

                                <br />
                                <span class="sub"><?php echo $elemento->codigo; ?></span>
                            </a>
                        </td>
                        <?php if($acl['editar'] || $acl['eliminar']){ ?>
                        <td>
                            <?php if($acl['editar']){ ?>
                            <a href="<?php echo $path . 'personal/editar/' . $elemento->id?>"
                               alt="Editar datos del personal" title="Editar datos del personal">
                               <img src="<?php echo $path?>public/img/sp5/editar.png" />
                            </a>
                            <?php } ?>
                            <?php if($acl['eliminar']){ ?>
                            <a href="<?php echo $path . 'personal/eliminar/' . $elemento->id?>"
                               alt="Eliminar toda la informacion del personal" title="Eliminar toda la informacion del personal">
                               <img src="<?php echo $path?>public/img/sp5/eliminar.png" />
                            </a>
                            <?php } ?>
                        </td>
                        <?php } ?>
                    </tr>
                    <?php
                        $i++;
                    }
                    ?>
                </table>
        <?php } else { ?>
                <p class="info"><br />No hay registros que mostrar...</p>
        <?php } ?>
        <div id="pages">
            <?php foreach($paginador->botones() as $boton){ ?>
                 <a  href="<?php echo $path . $boton->url() ?>"
                    title="Ir a la p&aacute;gina <?php echo $boton->titulo() ?>"
                    class="<?php echo $boton->estilo() ?>">
                    <?php echo $boton->etiqueta() ?>
                </a>
            <?php }?>
        </div>
    </div>
</div>