<?php $path = KUMBIA_PATH; ?>
<div id="primary">
    <div class="content">
        <h1>Simula avance del ciclo <?php echo $ciclo->numero?></h1>
        <div id="options-bar">
            <div id="options">
                <a href="<?php echo $path ?>ciclos">Volver
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
                </a>
            </div>
        </div>
        <?php switch($option) {
                case 'captura': ?>
                <form action="<?php echo $path ?>ciclos/simulaavance/" id="frm_status" method="post">
                    <input type="hidden" name="id" id="id" value="<?php echo $ciclo->id ?>" />
                    <p class="error">
                        Se dispone a realizar el avance del ciclo
                        <?php
                        echo $ciclo->numero;
                        ?>
                        <br />
                        <strong>&iquest;Desea continuar?</strong>
                    </p>
                    <div id="botones">
                        <input type="button" id="aceptar" value="Aceptar">
                        <input type="button" id="cancelar" value="Cancelar">
                    </div>
                </form>
            <?php  break; ?>
            <?php case 'exito': ?>
                <p class="info"><br />La simulacion del avance del ciclo se realizo correctamente
                <br/>
                <?php if($archivo!="" && file_exists($archivo)){ ?>
                    <a href="<?php echo $link; ?>">Obtener bitacora del cierre</a>
                <?php }else{ ?>
                    No se pudo obtener la bitacora del cierre.
                <?php } ?>
                .</p>
            <?php  break; ?>
            <?php case 'error':
                  default:
            ?>
                <p class="error">Ha ocurrido un error al intentar realizar el avance del ciclo.<br />
                <?php echo $error ?>
                </p>
            <?php  break; ?>
        <?php } ?>
    </div>
</div>