<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Status del ciclo <?php echo $ciclo->numero?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>ciclos">Volver
				<img src="<?php echo $path?>public/img/sp5/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) {
				case 'captura': ?>
				<form action="<?php echo $path ?>ciclos/status/" id="frm_status" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $ciclo->id ?>" />
					<p class="error">
						Se dispone a cambiar el status del ciclo a:
						<?php if($ciclo->activo == 1){ ?>
						<span class="false">Inactivo</span>
						<?php }else{ ?>
						<span class="true">Activo</span>
						<?php } ?>.
						<br />
						Si existe algun otro ciclo activo se pondra inactivo.
						<br />
						<strong>&iquest;Desea continuar?</strong>
					</p>
					<div id="botones">
						<input type="button" id="aceptar" value="Aceptar">
						<input type="button" id="cancelar" value="Cancelar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El status del ciclo se actualiz&oacute; correctamente.</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error">Ha ocurrido un error al intentar modificar el status del ciclo.<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>