<?php $css_path = KUMBIA_PATH . 'css/' ?>
<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv='Content-type' content='text/html; charset=utf-8' />
  <title>HEKADEMOS <?php echo ucfirst($controlador) ?></title>
  <link rel="shortcut icon" href="<?php echo "http://" . $_SERVER["SERVER_NAME"].KUMBIA_PATH . 'favicon.ico'?>" />
  <link href="<?php echo $css_path ?>tripoli.base.css" type="text/css" rel="stylesheet">
  <link href="<?php echo $css_path ?>tripoli.type.css" type="text/css" rel="stylesheet">
  <link href="<?php echo $css_path ?>tripoli.visual.css" type="text/css" rel="stylesheet">
  <link href="<?php echo $css_path ?>tripoli.layout.css" type="text/css" rel="stylesheet">
  <!--[if IE]><link rel="stylesheet" type="text/css" href="<?php echo $css_path ?>tripoli.base.ie.css"><![endif]-->
 <?php content() ?>
</html>