<?php $path = KUMBIA_PATH;
    //echo count($a)."<br/>";
    //echo count($p)."<br/>";
    //echo count($alumnos)."<br/>";
    //echo $sql;
    //echo $option;
    //echo $busqueda->campo("inconsistencia");
    //echo "<br/>"."Total: ".count($inconsistencias)."/".$pagina->total();
    //var_dump($inconsistencias);
?>
<div id="primary">
    <div class="content">
        <h1>
        <?php if($option=="vista"){ ?>
        <?php echo $pagina->total(); ?> Inconsistencia<?php echo ($pagina->total() == 1 ? '' : 's'); ?> del dia <a id="fecha" href="javascript:;"><?php echo $fecha; ?></a>
        <?php }else{ ?>
         Inconsistencias del dia <a id="fecha" href="javascript:;"><?php echo $fecha; ?></a>
        <?php } ?>
        </h1>
        <div id="options-bar">
            <div id="options">
            <a href="<?php echo $path ?>es">Volver a accesos
                <img src="<?php echo $path?>public/img/sp5/volver.png"/>
            </a> /
            <?php if($option!="error"){ ?>
            <a href="<?php echo $path ?>es/inconsistencias_exportar">Exportar
                <img src="<?php echo $path?>public/img/sp5/excel.png"/>
            </a> /
            <?php } ?>
            <a href="javascript:;" id="cicloBtn" title="Cambiar de ciclo escolar" alt="Cambiar de ciclo escolar">
                    Ciclo:
                </a>
                <div id="cicloActual"><?php echo $ciclo->numero?></div>
                <div id="cicloSel" style="display:none">
                    <form id="frm_ciclo" method="post" action="<?php echo $path ?>sistema/seleccionar">
                    <fieldset>
                        <input type="hidden" name="controlador" value="<?php echo $controlador ?>" />
                        <input type="hidden" name="accion" value="<?php echo $accion ?>" />
                        <select name="ciclo" id="cicloSelect">
                            <?php foreach($ciclos as $ccl){?>
                            <option value="<?php echo $ccl->id?>"
                                    <?php if($ccl->id == $ciclo->id){ ?>selected="selected"<?php } ?>>
                                    <?php echo $ccl->numero?>
                            </option>
                            <?php } ?>
                        </select>
                    </fieldset>
                    </form>
                </div>

            </div>

            <div id="search" >
                <form action="<?php echo $path ?>es/inconsistencias/<?php echo $date; ?>" method="post" id="frm_search">
                    <fieldset>
                    <input type="hidden" name="kumbia_path" id="kumbia_path"  value="<?php echo $path ?>"/>
                      <input type="hidden" name="date" id="date" value="<?php echo $date ?>"/>
                        <label for="tipo">Tipo</label>
                        <select name="tipo" id="tipo">
                            <option value="P" <?php if($busqueda->campo('tipo') == "P"){ ?>selected="selected"<?php } ?>>Profesores</option>
                            <option value="A" <?php if($busqueda->campo('tipo') == "A"){ ?>selected="selected"<?php } ?>>Alumnos</option>
                            <?php foreach($tipos as $tipo){ ?>
                            <option value="<?php echo $tipo->id; ?>" <?php if($busqueda->campo('tipo') == $tipo->id){ ?>selected="selected"<?php } ?>><?php echo $tipo->nombre ?></option>
                            <?php } ?>
                        </select>
                        <label for="inconsistencia">Inconsistencia</label>
                        <select name="inconsistencia" id="inconsistencia">
                            <option value="T" <?php if($busqueda->campo('inconsistencia') == "T"){ ?>selected="selected"<?php } ?>>Todas</option>
                            <option value="S" <?php if($busqueda->campo('inconsistencia') == "S"){ ?>selected="selected"<?php } ?>>Sin accesos</option>
                            <option value="A" <?php if($busqueda->campo('inconsistencia') == "A"){ ?>selected="selected"<?php } ?>>Accesos impares</option>
                            <option value="E" <?php if($busqueda->campo('inconsistencia') == "E"){ ?>selected="selected"<?php } ?>>Entradas/Salidas</option>
                        </select>
                        <label for="codigo">C&oacute;digo</label>
                        <input 
                            type="text" 
                            name="codigo" 
                            id="codigo" 
                            value="<?php echo $busqueda->campo('codigo') ?>" 
                            size="20" 
                            maxlength="20" />

                        <label for="nombre">Nombre</label>
                        <input type="text" name="nombre" id="nombre" value="<?php echo $busqueda->campo('nombre') ?>" size="15" maxlength="70" />
                        <br/>
                        <br/>
                        <div id="opciones_alumno" style="display:none">
                        <label for="grado">Grado</label>
                        <select name="grado" id="grado">
                            <option></option>
                            <option value="1" <?php if($busqueda->campo('grado') == 1){ ?>selected="selected"<?php } ?>>1</option>
                            <option value="2" <?php if($busqueda->campo('grado') == 2){ ?>selected="selected"<?php } ?>>2</option>
                            <option value="3" <?php if($busqueda->campo('grado') == 3){ ?>selected="selected"<?php } ?>>3</option>
                            <option value="4" <?php if($busqueda->campo('grado') == 4){ ?>selected="selected"<?php } ?>>4</option>
                            <option value="5" <?php if($busqueda->campo('grado') == 5){ ?>selected="selected"<?php } ?>>5</option>
                            <option value="6" <?php if($busqueda->campo('grado') == 6){ ?>selected="selected"<?php } ?>>6</option>
                        </select>
                        <label for="letra">Letra</label>
                        <input type="text" name="letra" id="letra" value="<?php echo $busqueda->campo('letra') ?>" size="3" maxlength="1" />
                        <label for="turno">Turno</label>
                        <select name="turno" id="turno">
                            <option></option>
                            <option value="M" <?php if($busqueda->campo('turno') == 'M'){ ?>selected="selected"<?php } ?>>M</option>
                            <option value="V" <?php if($busqueda->campo('turno') == 'V'){ ?>selected="selected"<?php } ?>>V</option>
                            <option value="N" <?php if($busqueda->campo('turno') == 'N'){ ?>selected="selected"<?php } ?>>N</option>
                        </select>
                        <label for="oferta_id">Oferta</label>
                        <select name="oferta_id" id="oferta_id">
                            <option></option>
                            <?php foreach($ofertas as $oferta){ ?>
                            <option value="<?php echo $oferta->id; ?>" <?php if($busqueda->campo('oferta_id') == $oferta->id){ ?>selected="selected"<?php } ?>><?php echo $oferta->nombre; ?></option>
                            <?php } ?>
                        </select>
                        </div>
                        <br/>
                        <input type="submit" id="btn_submit" value="Filtrar" />
                        <input type="reset" id="reset" value="Quitar filtros" />
                    </fieldset>
                </form>
            </div>

        </div>

                <?php switch($option) {
         case "vista": ?>
        <?php if($registros>0){ ?>
    <table>
    <tr><th>Foto</th><th>Codigo</th><th>Nombre</th><th>Inconsistencia</th></tr>
    <?php
         $i=0;
     foreach($inconsistencias as $u){ ?>
        <tr class="<?php echo ($i%2 == 0 ? '' : 'odd') ?>">
            <td><a href="<?php echo $u->foto  ?>"
                               rel="lightbox[]"
                               title="<?php echo $u->ap . ' ' . $u->am . ' ' . $u->nombre ?>"
                               alt="<?php echo $u->ap . ' ' . $u->am . ' ' . $u->nombre ?>">
                                <img src="<?php echo $u->foto ?>" class="thumb"/>
                            </a>
            </td>
            <td><?php echo $u->codigo; ?></td>
            <td><?php echo $u->nombre(); ?></td>
            <td>
            <?php if($u->tarjeta!=''){?>
            <a href="<?php echo $path."es/dia/".$u->tarjeta."/".$date ?>" title="Ver detalle" alt="Ver detalle" >
            <?php echo $pagina->obtenError($u->codigo); ?>
            </a>
            <?php }else{ ?>
            <?php echo $pagina->obtenError($u->codigo); ?>
            <?php } ?>
            </td>
        </tr>
    <?php
        $i++;
     } ?>
    </table>
    <div id="pages">
            <?php foreach($pagina->botones() as $boton){ ?>
                 <a  href="<?php echo $path . $boton->url() ?>"
                    title="Ir a la p&aacute;gina <?php echo $boton->titulo() ?>"
                    class="<?php echo $boton->estilo() ?>">
                    <?php echo $boton->etiqueta() ?>
                </a>
            <?php }?>
        </div>
    <?php }else{ ?>
        <br/><br/>
        <p class="error" >
        <br/>
        No existe ninguna inconsistencia.
        </p>

    <?php } ?>

        <?php break; ?>
        <?php case "default": ?>
        <?php case "error": ?>
        <p class="error" >
        <br/>
        <?php echo $error;  ?>
        </p>
        <?php break; ?>
        <?php } ?>

    </div>
</div>