<?php
Kumbia :: import('app.componentes.*');
$path = KUMBIA_PATH;
$css_path = $path . 'css/';
$js_path = $path . 'javascript/';
$vista = ($accion == '' ? 'index' : $accion);
$menu = Session :: get_data('usr.menu');
$template=new Template();
?>
 <link href="<?php echo $css_path ?>nav.css" type="text/css" rel="stylesheet">
  <link href="<?php echo $css_path ?>style.css" type="text/css" rel="stylesheet">
  <link href="<?php echo $css_path ?>print.css" type="text/css" rel="stylesheet" media="print">
  <link href="<?php echo $css_path ?>calendar.css" type="text/css" rel="stylesheet">
  <link href="<?php echo $css_path ?>lightbox/lightbox.css" type="text/css" rel="stylesheet">
   <link href="<?php echo $css_path ?>tooltips/tooltips.css" type="text/css" rel="stylesheet">
<?php if(file_exists('public/css/' . $controlador . '.css')){?>
  <link href="<?php echo $css_path . $controlador ?>.css" type="text/css" rel="stylesheet">
<?php }?>
<?php if(file_exists('public/css/' . $controlador . '.' . $vista . '.css')){?>
  <link href="<?php echo $css_path . $controlador . '.' . $vista ?>.css" type="text/css" rel="stylesheet">
<?php }?>
<?php if(file_exists('public/css/' . $controlador . '.' . $vista . '.print.css')){?>
  <link href="<?php echo $css_path . $controlador . '.' . $vista ?>.print.css" type="text/css" rel="stylesheet" media="print">
<?php }?>
  <script type="text/javascript" src="<?php echo $js_path ?>scriptaculous/prototype.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>scriptaculous/scriptaculous.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>scriptaculous/effects.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>event/adddomloadevent.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>calendar/calendar.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>calendar/calendar-setup.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>calendar/calendar-es.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>lightbox/lightbox.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>system/principal.js" /></script>
  <script type="text/javascript" src="<?php echo $js_path ?>tooltips/tooltips.js" /></script>
<?php if(file_exists('public/javascript/system/' . $controlador . '.js')){?>
  <script type="text/javascript" src="<?php echo $js_path . 'system/' . $controlador ?>.js" /></script>
<?php }?>
<?php if(file_exists('public/javascript/system/' . $controlador . '.' . $vista . '.js')){?>
  <script type="text/javascript" src="<?php echo $js_path . 'system/' . $controlador . '.' . $vista?>.js" /></script>
<?php }?>
</head>
<body class="l10 wide">
<div id="container">
    <div id="header">
        <div class="content">
            <div id="logo">
                <img src="<?php echo $path . $template->banner()?>" id="img_header" />
            </div>
            <div id="control">
                <?php echo Session :: get_data('usr.login') ?> /
                <a href="<?php echo $path ?>sistema/configuracion">Configuraci&oacute;n</a> /
                <a href="<?php echo $path ?>sistema/ayuda">Ayuda</a> /
                <a href="<?php echo $path ?>sesion/cerrar">Cerrar sesi&oacute;n</a>
            </div>
            <div id="menu_container">
            <?php if(is_array($menu)){?>
                <ul id="menu">
                    <?php foreach ($menu as $item) {?>
                        <li <?php echo ($controlador == $item ? 'id="active"' : '') ?>>
                            <a href="<?php echo $path . $item?>" alt="<?php echo $item ?>">
                                <?php echo ucfirst($item) ?>
                            </a>
                        </li>
                    <?php }?>
                </ul>
            <?php } ?>
            </div>
        </div>
    </div>
    <?php content() ?>
        <div id="footer">
        <div class="content" >
        <div style="float:right;margin-right:5px; margin-top:5px; margin-bottom: 2px;">
        <!--<a href="http://validator.w3.org/check?uri=referer"><img src="auth_files/valid-xhtml10-blue.png" alt="Valid XHTML 1.0 Strict" height="25" width="65"></a>-->
        <img style="float:left;margin-top:12px;margin-right:5px" alt="Hekademos" src="<?php echo KUMBIA_PATH; ?>public/img/sp5/hkd.png"/>
        <img style="height:32px;float:right;margin-top:2px" alt="Buho" src="<?php echo KUMBIA_PATH; ?>public/img/sp5/buho.png"/>
    </div>
    <div style="margin-right:80px;padding-top:15px;">
        <a style="text-decoration:none; font-weight:bold; font-size:10px; color:#4f2c5c" href="http://fipasoft.mx">
            http://hekademos.mx
        </a>
            
    </div>
        </div>
    </div>
</div>
</body>